// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_increment_values_cpp
Rcpp::NumericVector compute_increment_values_cpp(const Rcpp::NumericVector& values, const double reset_drop, const double min_pos, const double max_gap);
RcppExport SEXP _AquaCache_compute_increment_values_cpp(SEXP valuesSEXP, SEXP reset_dropSEXP, SEXP min_posSEXP, SEXP max_gapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< const double >::type reset_drop(reset_dropSEXP);
    Rcpp::traits::input_parameter< const double >::type min_pos(min_posSEXP);
    Rcpp::traits::input_parameter< const double >::type max_gap(max_gapSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_increment_values_cpp(values, reset_drop, min_pos, max_gap));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AquaCache_compute_increment_values_cpp", (DL_FUNC) &_AquaCache_compute_increment_values_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_AquaCache(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
