#' Add new raster series (auto-fetched models)
#'
#' Use this function to add a new series of rasters generated by a model, such as the RDPS or HRDPS models by ECCC.
#'
#' @param model The model producing the raster
#' @param parameter The parameter to import, exactly as you'd find in the FTP link for the model rasters. For example, check out the [HRDPS parameters](https://eccc-msc.github.io/open-data/msc-data/nwp_hrdps/readme_hrdps-datamart_en/). This must be something understood by the `source_fx` function.
#' @param start_datetime The datetime (as POSIXct) from which to look for rasters
#' @param source_fx The function to use for fetching new rasters. Must be an existing function in this package.
#' @param type The type of raster, 'forecast' or 'reanalysis'. Reanalysis rasters are kept forever, forecasts are replaced when a new one is issued.
#' @param source_fx_args Additional arguments to pass to the function, in the form "\{param1 = arg1\}, \{param2 = 'arg2'\}". Each parameter = value pair needs to be enclosed in curly brackets, which might be missing here. Do not deviate from this format!
#' @param con A connection to the database, created with [DBI::dbConnect()]. Leave NULL if you want to use the package default connection settings and have the connection automatically closed afterwards.
#'
#' @return TRUE if successful, and a new entry in the database with images fetched.
#' @export
#'

addACRasterSeries <- function(model, parameter, start_datetime, source_fx, type, source_fx_args = NA, con = NULL) {
  #function will add entry to raster_series_index, then trigger getNewRasters from the user-specified start_datetime

  if (!type %in% c("forecast", "reanalysis")) {
    stop("The 'type' parameter must be either 'forecast' or 'reanalysis'.")
  }
  
  if (is.null(con)) {
    con <- AquaConnect(silent = TRUE)
    on.exit(DBI::dbDisconnect(con))
  }
  
  exists <- DBI::dbGetQuery(con, paste0("SELECT raster_series_id FROM raster_series_index WHERE model = '", model, "' AND parameter = '", parameter, "';"))[1,1]
  if (!is.na(exists)) {
    stop("There is already an entry for that model and parameter in the raster_series_index table.")
  }
  insert <- data.frame(model = model,
                       parameter = parameter,
                       start_datetime = start_datetime,
                       last_new_raster = start_datetime,
                       end_datetime = start_datetime,
                       source_fx = source_fx,
                       type = type,
                       source_fx_args = source_fx_args,
                       active = TRUE)

  DBI::dbAppendTable(con, "raster_series_index", insert)
  # Get the newly created id
  res <- DBI::dbGetQuery(con, paste0("SELECT raster_series_id FROM raster_series_index WHERE model = '", model, "' AND parameter = '", parameter, "';"))[1,1]
  added <- getNewRasters(raster_series_ids = res, con = con)
  if (length(added) == 0) {
    DBI::dbExecute(con, paste0("DELETE FROM raster_series_index WHERE raster_series_id = ", res, ";"))
    warning("Failed to find or add new images. The new entry to table raster_series_index has been deleted.")
  } else {
    first_new <- DBI::dbGetQuery(con, paste0("SELECT MIN(valid_from) FROM rasters_reference WHERE raster_series_id = ", res, ";"))[1,1]
    DBI::dbExecute(con, paste0("UPDATE raster_series_index SET start_datetime = '", first_new, "' WHERE raster_series_id = ", res, ";"))
    message("Added new raster series for model ", model, " and parameter ", parameter, ". The new raster_series_id is ", res, ".")
  }
}
