#' Add new raster series (auto-fetched models)
#'
#' Use this function to add a new series of rasters generated by a model, such as the RDPS or HRDPS models by ECCC.
#'
#' @param model The model producing the raster
#' @param start_datetime The datetime (as POSIXct) from which to look for rasters
#' @param source_fx The function to use for fetching new rasters Must be an existing function in this package.
#' @param source_fx_args Additional arguments to pass to the function, in the form "{param1 = arg1}, {param2 = 'arg2'}". Each parameter = value pair needs to be enclosed in curly brackets, which might be missing here. Do not deviate from this format!
#' @param public Should the rasters be publicly visible?
#' @param public_delay A period in ISO 8601 format by which to delay public visibility of images.
#' @param con A connection to the database, created with [DBI::dbConnect()] or using the utility function [hydrometConnect()].
#'
#' @return TRUE if successful, and a new entry in the database with images fetched.
#' @export
#'

addHydrometRasterSeries <- function(model, start_datetime, source_fx, source_fx_args = NA, public = TRUE, public_delay = NA, con = hydrometConnect(silent = TRUE)) {
  #function will add entry to raster_series_index, then trigger getNewRasters from the user-specified start_datetime

  on.exit(DBI::dbDisconnect(con))
  exists <- DBI::dbGetQuery(con, paste0("SELECT raster_series_id FROM raster_series_index WHERE model = '", model, "';"))[1,1]
  if (!is.na(exists)){
    stop("There is already an entry for that model in the raster_series_index table.")
  }
  insert <- data.frame(model = model,
                       public = public,
                       start_datetime = start_datetime,
                       last_new_raster = start_datetime,
                       public_delay = public_delay,
                       source_fx = source_fx,
                       source_fx_args = source_fx_args)

  DBI::dbAppendTable(con, "raster_series_index", insert)
  res <- DBI::dbGetQuery(con, paste0("SELECT raster_series_id FROM raster_series_index WHERE location = '", location, "' AND img_type = 'auto'"))[1,1]
  added <- getNewRasters(raster_series_id = res, con = con)
  if (length(added) == 0){
    warning("Failed to find or add new images. The new entry to table raster_series_index has been deleted.")
    DBI::dbExecute(con, paste0("DELETE FROM raster_series_index WHERE img_meta_id = ", res, ";"))
  } else {
    first_new <- DBI::dbGetQuery(con, paste0("SELECT MIN(valid_from) FROM rasters_reference WHERE raster_series_id = ", res, ";"))[1,1]
    DBI::dbExecute(con, paste0("UPDATE raster_series_index SET start_datetime = '", first_new, "' WHERE raster_series_id = ", res, ";"))
    message("Added new raster series for model ", model, ". The new raster_series_id is ", res, ".")
  }
}
