# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_increment_values_cpp <- function(values, reset_drop, min_pos, max_gap) {
    .Call(`_AquaCache_compute_increment_values_cpp`, values, reset_drop, min_pos, max_gap)
}

