# Patch 53: Adding cross-section, verticals, and points schema to aquacache database

check <- DBI::dbGetQuery(con, "SELECT SESSION_USER")

if (check$session_user != "postgres") {
  stop(
    "You do not have the necessary privileges for this patch. Connect as postgres user to make this work."
  )
}

# TODO: set official patch number
message(
  "Working on patch 53:  adding cross-section, verticals, and points tables to the discrete schema."
)

if (dbTransCheck(con)) {
  stop(
    "A transaction is already in progress. Please commit or rollback the current transaction before applying this patch."
  )
}

active <- FALSE
active <- dbTransBegin(con)

tryCatch(
  {
    # check for the following:
    # public.locations exists
    # information.version_info exists
    # cross section tables do not already exist
    check <- DBI::dbGetQuery(
      con,
      "SELECT
        to_regclass('public.locations') IS NOT NULL AS has_locations,
        to_regclass('information.version_info') IS NOT NULL AS has_version_info,
        to_regclass('discrete.cross_sections') IS NULL AS no_cross_sections,
        to_regclass('discrete.cross_section_verticals') IS NULL AS no_cross_section_verticals,
        to_regclass('discrete.cross_section_points') IS NULL AS no_cross_section_points"
    )

    if (
      !isTRUE(check$has_locations[[1]]) ||
        !isTRUE(check$has_version_info[[1]]) ||
        !isTRUE(check$no_cross_sections[[1]]) ||
        !isTRUE(check$no_cross_section_verticals[[1]]) ||
        !isTRUE(check$no_cross_section_points[[1]])
    ) {
      stop(
        "Patch 53 requires public.locations and information.version_info to exist, and cross-section tables must not already exist."
      )
    }

    # creating cross-sections table
    # Table: Cross Sections
    # Parent Table: public.locations
    # contains summary information for a cross section measurement.
    # one row = one single cross-section at one date

    message("Creating cross_sections table...")

    DBI::dbExecute(
      con,
      "
      CREATE TABLE discrete.cross_sections (
        xsection_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,

        location_id int4 NOT NULL,
        datetime timestamptz NOT NULL,

        wetted_width_m numeric NULL,
        wetted_width_calculated_m numeric NULL,
        total_area_m2 numeric NULL, --area in icethick db, manual entry not dep on other tables.
        total_area_calculated_m2 numeric NULL, --populated from other tables on trigger
        net_area_m2 numeric NULL, -- new val, area not including ice thickness nor slush
        net_area_calculated_m2 numeric,
        avg_total_depth_m numeric NULL,
        avg_total_depth_calculated_m numeric NULL,    
        avg_velocity_m_s numeric NULL,
        avg_velocity_calculated_m_s numeric NULL,
        discharge_m3_s numeric NULL,
        discharge_calculated_m3_s numeric NULL,
        ice_avg_thickness_m numeric NULL,
        ice_avg_thickness_calculated_m numeric NULL,
        ice_area_m2 numeric NULL, -- new derived col, from verticals 
        ice_area_calculated_m2 numeric NULL,
        slush_avg_thickness_m numeric NULL,
        slush_avg_thickness_calculated_m numeric NULL,
        slush_area_m2 numeric NULL,
        slush_area_calculated_m2 numeric NULL,
        use_calculated_values boolean DEFAULT true NOT NULL,
        source_system text NULL, 
        source_measurement_id text NULL,
        note text NULL,
        created timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
        modified timestamptz NULL,
        created_by text DEFAULT CURRENT_USER NOT NULL,
        modified_by text NULL,

        CONSTRAINT cross_sections_pkey
            PRIMARY KEY (xsection_id),

        CONSTRAINT cross_sections_location_id_fkey
            FOREIGN KEY (location_id)
            REFERENCES public.locations(location_id)
            ON DELETE CASCADE
            ON UPDATE CASCADE,

        -- CONSTRAINT cross_sections_unique_location_datetime
        --    UNIQUE (location_id, datetime),

        CONSTRAINT cross_sections_unique_source UNIQUE (source_system, source_measurement_id)

      );
      "
    )

    # adding table and column comments for cross-sections table
    message("Adding comments to cross_sections table...")

    comments_cross_sections <- c(
      "COMMENT ON TABLE discrete.cross_sections IS 'Primary table for storing stream cross-section data. Links to locations table, and serves as parent table for cross_section_verticals and cross_section_points tables. each row contains summary information for a single cross section at a set location and date.';",
      "COMMENT ON COLUMN discrete.cross_sections.wetted_width_m IS 'Numeric value denoting width of stream, using wetted area as reference for start/end of measurement. Field used for manual data entry (if no vertical width data available)';",
      "COMMENT ON COLUMN discrete.cross_sections.wetted_width_calculated_m IS 'Numeric value denoting width of stream, using wetted area as reference for start/end of measurement. Field automatically filled from available cross_section_verticals fields';",
      "COMMENT ON COLUMN discrete.cross_sections.total_area_m2 IS 'Value denoting total area of the cross section, including water, slush, and ice area. Field used for manual data input if no Vertical-level data is present.';",
      "COMMENT ON COLUMN discrete.cross_sections.total_area_calculated_m2 IS 'Value denoting total area of the cross section, including water, slush, and ice area. Field automatically populated from available Vertical-level data';",
      "COMMENT ON COLUMN discrete.cross_sections.net_area_m2 IS 'Value denoting area of cross section containing flowing water (ie not including ice and slush area). Field used for manual data input if no Vertical-level data is present.';",
      "COMMENT ON COLUMN discrete.cross_sections.net_area_calculated_m2 IS 'Value denoting area of cross section containing flowing water (ie not including ice and slush area). Field automatically populated from available Vertical-level data';",
      "COMMENT ON COLUMN discrete.cross_sections.avg_total_depth_m IS 'Value denoting the average depth of flowing water in the stream, measured from the bottom of the stream to the waterline. Field used for manual data input if no Vertical-level data is present.';",
      "COMMENT ON COLUMN discrete.cross_sections.avg_total_depth_calculated_m IS 'Value denoting the average depth of flowing water in the stream, measured from the bottom of the stream to the waterline. Field automatically populated from available Vertical-level data';",
      "COMMENT ON COLUMN discrete.cross_sections.avg_velocity_m_s IS 'Value denoting the average velocity of flowing water in the stream, excluding ice and slush layers. Field used for manual data input if no Vertical-level data is present.';",
      "COMMENT ON COLUMN discrete.cross_sections.avg_velocity_calculated_m_s IS 'Value denoting the average velocity of flowing water in the stream, excluding ice and slush layers. Field automatically populated from available Vertical-level data';",
      "COMMENT ON COLUMN discrete.cross_sections.discharge_m3_s IS 'Value denoting the average flowrate of flowing water in the stream, excluding ice and slush layers. Field used for manual data input if no Vertical-level data is present.';",
      "COMMENT ON COLUMN discrete.cross_sections.discharge_calculated_m3_s IS 'Value denoting the average flowrate of flowing water in the stream, excluding ice and slush layers. Field automatically populated from available Vertical-level data.';",
      "COMMENT ON COLUMN discrete.cross_sections.ice_avg_thickness_m IS 'Denotes the average thickness of ice located above the stream, if present. Field used for manual data input if no Vertical-level data is present.';",
      "COMMENT ON COLUMN discrete.cross_sections.ice_avg_thickness_calculated_m IS 'Denotes the average thickness of ice located above the stream, if present. Field automatically populated from available Vertical-level data.';",
      "COMMENT ON COLUMN discrete.cross_sections.ice_area_m2 IS 'Denotes the overall area of ice present in the stream cross section. Field used for manual data input if no Vertical-level data is present.';",
      "COMMENT ON COLUMN discrete.cross_sections.ice_area_calculated_m2 IS 'Denotes the overall area of ice present in the stream cross section. Field automatically populated from available Vertical-level data.';",
      "COMMENT ON COLUMN discrete.cross_sections.slush_avg_thickness_m IS 'Denotes the average thickness of slush ice located in the stream cross section, if present. Field used for manual data input if no Vertical-level data is present.';",
      "COMMENT ON COLUMN discrete.cross_sections.slush_avg_thickness_calculated_m IS 'Denotes the average thickness of slush ice located in the stream cross section, if present. Field automatically populated from available Vertical-level data.';",
      "COMMENT ON COLUMN discrete.cross_sections.slush_area_m2 IS 'Denotes the overall area of slush present in the stream cross section. Field used for manual data input if no Vertical-level data is present.';",
      "COMMENT ON COLUMN discrete.cross_sections.slush_area_calculated_m2 IS 'Denotes the overall area of ice present in the stream cross section. Field automatically populated from available Vertical-level data.';",
      "COMMENT ON COLUMN discrete.cross_sections.source_system IS 'Field to denote the source of the cross section data, Whether single input or from historical database.';",
      "COMMENT ON COLUMN discrete.cross_sections.source_measurement_id IS 'Field used to store any previous historical key for cross section measurements imported to Aquacache, in case future traceback to historical records is required';",
      "COMMENT ON COLUMN discrete.cross_sections.note IS 'Free-text note field for context that does not fit a more structured column.';",
      "COMMENT ON COLUMN discrete.cross_sections.created IS 'Timestamp when the row was created.';",
      "COMMENT ON COLUMN discrete.cross_sections.modified IS 'Timestamp when the row was last updated.';",
      "COMMENT ON COLUMN discrete.cross_sections.created_by IS 'Database role or application actor recorded as the row creator.';",
      "COMMENT ON COLUMN discrete.cross_sections.modified_by IS 'Database role or application actor recorded as the last modifier.';"
    )

    for (comment_sql in comments_cross_sections) {
      DBI::dbExecute(con, comment_sql)
    }

    # # Older expression for when manual and calculated fields were both pulled from same table
    # DBI::dbExecute(
    #   con,
    #   "
    #   CREATE VIEW discrete.cross_sections_view AS
    #   SELECT
    #     xsection_id,
    #     location_id,
    #     datetime,
    #     CASE
    #       WHEN use_calculated_values
    #       THEN COALESCE(wetted_width_calculated_m, wetted_width_m)
    #       ELSE COALESCE(wetted_width_m, wetted_width_calculated_m)
    #       END AS wetted_width_m,
    #     CASE
    #       WHEN use_calculated_values
    #       THEN COALESCE(total_area_calculated_m2, total_area_m2)
    #       ELSE COALESCE(total_area_m2, total_area_calculated_m2)
    #       END AS total_area_m2,
    #     CASE
    #       WHEN use_calculated_values
    #       THEN COALESCE(net_area_calculated_m2, net_area_m2)
    #       ELSE COALESCE(net_area_m2, net_area_calculated_m2)
    #       END AS net_area_m2,
    #     CASE
    #       WHEN use_calculated_values
    #       THEN COALESCE(avg_total_depth_calculated_m, avg_total_depth_m)
    #       ELSE COALESCE(avg_total_depth_m, avg_total_depth_calculated_m)
    #       END AS avg_total_depth_m,
    #     CASE
    #       WHEN use_calculated_values
    #       THEN COALESCE(avg_velocity_calculated_m_s, avg_velocity_m_s)
    #       ELSE COALESCE(avg_velocity_m_s, avg_velocity_calculated_m_s)
    #       END AS avg_velocity_m_s,
    #     CASE
    #       WHEN use_calculated_values
    #       THEN COALESCE(discharge_calculated_m3_s, discharge_m3_s)
    #       ELSE COALESCE(discharge_m3_s, discharge_calculated_m3_s)
    #       END AS discharge_m3_s,
    #     CASE
    #       WHEN use_calculated_values
    #       THEN COALESCE(ice_avg_thickness_calculated_m, ice_avg_thickness_m)
    #       ELSE COALESCE(ice_avg_thickness_m, ice_avg_thickness_calculated_m)
    #       END AS ice_avg_thickness_m,
    #     CASE
    #       WHEN use_calculated_values
    #       THEN COALESCE(ice_area_calculated_m2, ice_area_m2)
    #       ELSE COALESCE(ice_area_m2, ice_area_calculated_m2)
    #       END AS ice_area_m2,
    #     CASE
    #       WHEN use_calculated_values
    #       THEN COALESCE(slush_avg_thickness_calculated_m, slush_avg_thickness_m)
    #       ELSE COALESCE(slush_avg_thickness_m, slush_avg_thickness_calculated_m)
    #       END AS slush_avg_thickness_m,
    #     CASE
    #       WHEN use_calculated_values
    #       THEN COALESCE(slush_area_calculated_m2, slush_area_m2)
    #       ELSE COALESCE(slush_area_m2, slush_area_calculated_m2)
    #       END AS slush_area_m2,
    #     use_calculated_values,
    #     source_system,
    #     source_measurement_id,
    #     note,
    #     created,
    #     modified,
    #     created_by,
    #     modified_by

    #   FROM discrete.cross_sections
    #   "
    # )

    # creating verticals table
    # Table: Vertical
    # Parent Table: discrete.cross_sections
    # contains vertical level data (velocity, flowrate, icethickness, etc)
    # one row = one single vertical related to one cross section ID

    message("Creating cross_section_verticals table...")

    DBI::dbExecute(
      con,
      "
      CREATE TABLE discrete.cross_section_verticals (
        vertical_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,

        xsection_id int4 NOT NULL,
        measurement_time timestamptz NULL,

        distance_to_reference_m numeric NULL,
        distance_to_waterline_m numeric NOT NULL, 
        reference_bank text DEFAULT 'right' NOT NULL, 

        panel_flowing_water_depth_m numeric, 
        ice_thickness_m numeric NULL,
        water_surface_to_bottom_ice_m numeric NULL,
        slush_ice_thickness_m numeric NULL,
        
        panel_width_m numeric NULL,
        panel_area_m2 numeric NULL,

        panel_mean_velocity_m_s numeric NULL,
        panel_mean_velocity_calculated_m_s numeric NULL,
        panel_angle_of_flow_deg numeric NULL,
        panel_discharge_m3_s numeric NULL,
        panel_discharge_calculated_m3_s numeric, 

        use_calculated_values boolean DEFAULT true NOT NULL,

        source_vertical_id text NULL,
        note text NULL,

        created timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
        modified timestamptz NULL,
        created_by text DEFAULT CURRENT_USER NOT NULL,
        modified_by text NULL,

        CONSTRAINT cross_section_verticals_pkey
            PRIMARY KEY (vertical_id),

        CONSTRAINT cross_section_verticals_xsection_id_fkey
            FOREIGN KEY (xsection_id)
            REFERENCES discrete.cross_sections(xsection_id)
            ON DELETE CASCADE
            ON UPDATE CASCADE,

        CONSTRAINT cross_section_verticals_reference_bank_check
            CHECK (reference_bank IN ('left', 'right')), 

            CONSTRAINT cross_section_verticals_unique_distance_bank_orientation
            UNIQUE NULLS NOT DISTINCT (
                xsection_id,
                distance_to_reference_m,
                distance_to_waterline_m
            ),

        CONSTRAINT cross_section_verticals_unique_source
            UNIQUE (xsection_id, source_vertical_id)

      );
      "
    )

    # adding table and column comments for verticals table
    message("Adding comments to cross_section_verticals table...")

    comments_cross_section_verticals <- c(
      "COMMENT ON TABLE discrete.cross_section_verticals IS 'Secondary Table for cross-section data, containing vertical panel level data. links to cross_sections table via cross_section_id, and serves as parent table for cross_sections_points table. Each row contains data for a single vertical panel of a single cross-section for a certain location and time, including panel dimension data, water/slush/ice profile, and velocity/flowrate parameters.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.distance_to_reference_m IS 'Distance from the survey reference point used during measurement. Preserved primarily for compatibility with legacy Ice Thickness DB records.'",
      "COMMENT ON COLUMN discrete.cross_section_verticals.distance_to_waterline_m IS 'Denotes the horizontal distance from the center of the panel to the edge of the shoreline, in meters';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.reference_bank IS 'indicator for which bank distances for verticals are measured from. Right bank is default value.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.panel_flowing_water_depth_m IS 'value denoting vertical height of water column at panel location, from bottom of panel to top of flowing water.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.ice_thickness_m IS 'value denoting thickness of ice at panel location, if present';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.water_surface_to_bottom_ice_m IS 'value denoting distance of gap between water surface and bottom of ice layer, if present.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.slush_ice_thickness_m IS 'value denoting thickness of slush ice at panel location, if present';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.panel_width_m IS 'value denoting width of panel, in meters';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.panel_area_m2 IS 'value denoting are of panel containing flowing water, in meters. calculated as the panel width multiplied by panel flowing water depth';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.panel_mean_velocity_m_s IS 'average velocity of water flowing at panel location. Field used for manual data input if no points-level data is present.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.panel_mean_velocity_calculated_m_s IS 'Average velocity of water flowing at panel location. Field automatically populated from available points-level data.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.panel_angle_of_flow_deg IS 'value denoting the angle of the flow, relative to the angle normal from the panel.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.panel_discharge_m3_s IS 'value denoting the flow rate of water through the panel. Field used for manual data input if no points-level velocity data is available';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.panel_discharge_calculated_m3_s IS 'Value denoting the flow rate of water through the panel. field calculated based on the panel_mean_velocity_calculated_m_s field and panel area.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.source_vertical_id IS 'Field to denote the source of the cross section verticals data, Whether single input or from historical database.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.note IS 'Free-text note field for context that does not fit a more structured column.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.created IS 'Timestamp when the row was created.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.modified IS 'Timestamp when the row was last updated.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.created_by IS 'Database role or application actor recorded as the row creator.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.modified_by IS 'Database role or application actor recorded as the last modifier.';"
    )

    for (comment_sql in comments_cross_section_verticals) {
      DBI::dbExecute(con, comment_sql)
    }

    # # Previous version (coalesce based on values from same table)
    #
    #  DBI::dbExecute(
    #   con,
    #   "
    #   CREATE VIEW discrete.cross_section_verticals_view AS
    #   SELECT
    #     vertical_id,
    #     xsection_id,
    #     measurement_time,
    #     distance_to_waterline_m,
    #     reference_bank,
    #     panel_flowing_water_depth_m,
    #     ice_thickness_m,
    #     water_surface_to_bottom_ice_m,
    #     slush_ice_thickness_m,
    #     panel_width_m,
    #     panel_area_m2,
    #     CASE
    #       WHEN use_calculated_values
    #       THEN COALESCE(panel_mean_velocity_calculated_m_s, panel_mean_velocity_m_s)
    #       ELSE COALESCE(panel_mean_velocity_m_s, panel_mean_velocity_calculated_m_s)
    #       END AS panel_mean_velocity_m_s,
    #     panel_angle_of_flow_deg,
    #     CASE
    #       WHEN use_calculated_values
    #       THEN COALESCE(panel_discharge_calculated_m3_s, panel_discharge_m3_s)
    #       ELSE COALESCE(panel_discharge_m3_s, panel_discharge_calculated_m3_s)
    #       END AS panel_discharge_m3_s,
    #     use_calculated_values,
    #     source_vertical_id,
    #     note,
    #     created,
    #     modified,
    #     created_by,
    #     modified_by

    #   FROM discrete.cross_section_verticals
    #   "
    # )

    # creating points table
    # Table: Points
    # Parent Table: discrete.cross_section_verticals
    # contains points level data (point depth, velocity)
    # one row = one single point related to one vertical ID

    message("Creating cross_section_points table...")

    DBI::dbExecute(
      con,
      "
      CREATE TABLE discrete.cross_section_points (
        point_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,

        vertical_id int4 NOT NULL,

        position_on_water_panel numeric NOT NULL,
        depth_in_moving_water_m numeric NULL,

        velocity_m_s numeric NOT NULL,

        note text NULL,

        created timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
        modified timestamptz NULL,
        created_by text DEFAULT CURRENT_USER NOT NULL,
        modified_by text NULL,

        CONSTRAINT cross_section_points_pkey
            PRIMARY KEY (point_id),

        CONSTRAINT cross_section_points_vertical_id_fkey
            FOREIGN KEY (vertical_id)
            REFERENCES discrete.cross_section_verticals(vertical_id)
            ON DELETE CASCADE
            ON UPDATE CASCADE
        
      );
      "
    )

    # adding table and column comments for points table
    message("Adding comments to cross_section_points table...")

    comments_cross_section_points <- c(
      "COMMENT ON TABLE discrete.cross_section_points IS 'Tertiary table for storing cross-section data, containing individual point data within a cross section vertical. Links to cross_section_verticals via vertical_id. Each row contains data for a single point within a vertical of the cross section for a certain location and time, including depth of point and velocity.';",
      "COMMENT ON COLUMN discrete.cross_section_points.position_on_water_panel IS 'Denotes the proportion of the panel at which the point was measured as a decimal value from 0 - 1. referenced from ____';",
      "COMMENT ON COLUMN discrete.cross_section_points.depth_in_moving_water_m IS 'Denotes the depth at which point velocity was measured on the panel. Referenced from  _____';",
      "COMMENT ON COLUMN discrete.cross_section_points.velocity_m_s IS 'Velocity of water flowing at point location on panel.';",
      "COMMENT ON COLUMN discrete.cross_section_points.note IS 'Free-text note field for context that does not fit a more structured column.';",
      "COMMENT ON COLUMN discrete.cross_section_points.created IS 'Timestamp when the row was created.';",
      "COMMENT ON COLUMN discrete.cross_section_points.modified IS 'Timestamp when the row was last updated.';",
      "COMMENT ON COLUMN discrete.cross_section_points.created_by IS 'Database role or application actor recorded as the row creator.';",
      "COMMENT ON COLUMN discrete.cross_section_points.modified_by IS 'Database role or application actor recorded as the last modifier.';"
    )

    for (comment_sql in comments_cross_section_points) {
      DBI::dbExecute(con, comment_sql)
    }

    # Creating the following 4 Views
    # 1 cross_section_verticals_calculated: view of calculated fields for verticals table
    # 2 cross_section_verticals_view: view coalescing calculated & manual fields for verticals table
    # 3 cross_sections_calculated: view of calculated fields for cross section table
    # 4 cross_sections_view: view coalescing calculated & manuel fields for cross section table

    # VIEW 1: Create view of values calculated from verticals table
    message(
      "Creating view of calculated fields for cross section verticals table..."
    )

    DBI::dbExecute(
      con,
      "
      CREATE VIEW discrete.cross_section_verticals_calculated AS
      SELECT
          v.vertical_id,

          CASE
              WHEN v.panel_width_m IS NOT NULL
              AND v.panel_flowing_water_depth_m IS NOT NULL
              THEN v.panel_width_m * v.panel_flowing_water_depth_m
              ELSE NULL
          END AS panel_area_calculated_m2,

          AVG(p.velocity_m_s) AS panel_mean_velocity_calculated_m_s,

          CASE
              WHEN v.panel_width_m IS NOT NULL
              AND v.panel_flowing_water_depth_m IS NOT NULL
              AND AVG(p.velocity_m_s) IS NOT NULL
              THEN
                  (v.panel_width_m * v.panel_flowing_water_depth_m)
                  * AVG(p.velocity_m_s)
              ELSE NULL
          END AS panel_discharge_calculated_m3_s

      FROM discrete.cross_section_verticals v
      LEFT JOIN discrete.cross_section_points p
          ON v.vertical_id = p.vertical_id
      GROUP BY
          v.vertical_id,
          v.panel_width_m,
          v.panel_flowing_water_depth_m;
      "
    )

    # View 2: creating view for verticals table coalescing manual/calculated fields
    message(
      "Creating view of preferred values for cross section verticals table..."
    )

    DBI::dbExecute(
      con,
      "
      CREATE VIEW discrete.cross_section_verticals_view AS
      SELECT
          v.vertical_id,
          v.xsection_id,
          v.measurement_time,
          v.distance_to_reference_m,
          v.distance_to_waterline_m,
          v.reference_bank,

          v.panel_flowing_water_depth_m,
          v.ice_thickness_m,
          v.water_surface_to_bottom_ice_m,
          v.slush_ice_thickness_m,
          v.panel_width_m,
          
          CASE
              WHEN v.use_calculated_values
              THEN COALESCE(vc.panel_area_calculated_m2, v.panel_area_m2)
              ELSE COALESCE(v.panel_area_m2, vc.panel_area_calculated_m2)
          END AS panel_area_m2,

          CASE
              WHEN v.use_calculated_values
              THEN COALESCE(vc.panel_mean_velocity_calculated_m_s, v.panel_mean_velocity_m_s)
              ELSE COALESCE(v.panel_mean_velocity_m_s, vc.panel_mean_velocity_calculated_m_s)
          END AS panel_mean_velocity_m_s,

          v.panel_angle_of_flow_deg,

          CASE
              WHEN v.use_calculated_values
              THEN COALESCE(vc.panel_discharge_calculated_m3_s, v.panel_discharge_m3_s)
              ELSE COALESCE(v.panel_discharge_m3_s, vc.panel_discharge_calculated_m3_s)
          END AS panel_discharge_m3_s,

          v.source_vertical_id,
          v.note,
          v.created,
          v.modified,
          v.created_by,
          v.modified_by
      FROM discrete.cross_section_verticals v
      LEFT JOIN discrete.cross_section_verticals_calculated vc
          ON v.vertical_id = vc.vertical_id;
      "
    )

    # VIEW 3: Create view of values calculated from verticals table
    #note, cross section calculated values use vertical preferred-value View rather than cross_section_verticals table, to preserve manual-calculated value preference
    message("Creating view of calculated fields for cross section table...")
    DBI::dbExecute(
      con,
      "
      CREATE VIEW discrete.cross_sections_calculated AS
      SELECT
        cs.xsection_id,

        SUM(v.panel_width_m) AS wetted_width_calculated_m,

        SUM(v.panel_area_m2) AS net_area_calculated_m2,

        CASE
          WHEN SUM(v.panel_area_m2) IS NOT NULL
            OR SUM(v.panel_width_m * v.ice_thickness_m) IS NOT NULL
            OR SUM(v.panel_width_m * v.slush_ice_thickness_m) IS NOT NULL
          THEN
              COALESCE(SUM(v.panel_area_m2), 0)
            + COALESCE(SUM(v.panel_width_m * v.ice_thickness_m), 0)
            + COALESCE(SUM(v.panel_width_m * v.slush_ice_thickness_m), 0)
          ELSE NULL
        END AS total_area_calculated_m2,

        AVG(v.panel_flowing_water_depth_m) AS avg_total_depth_calculated_m,

        AVG(v.panel_mean_velocity_m_s) AS avg_velocity_calculated_m_s,

        SUM(v.panel_discharge_m3_s) AS discharge_calculated_m3_s,

        AVG(v.ice_thickness_m) AS ice_avg_thickness_calculated_m,

        SUM(v.panel_width_m * v.ice_thickness_m) AS ice_area_calculated_m2,

        AVG(v.slush_ice_thickness_m) AS slush_avg_thickness_calculated_m,

        SUM(v.panel_width_m * v.slush_ice_thickness_m) AS slush_area_calculated_m2

      FROM discrete.cross_sections cs
      LEFT JOIN discrete.cross_section_verticals_view v
        ON cs.xsection_id = v.xsection_id
      
      GROUP BY cs.xsection_id;
      "
    )

    # VIEW 4: Create view of cross section table coalescing manual/calculated fields
    message("Creating view of preferred values for cross section table...")

    DBI::dbExecute(
      con,
      "
      CREATE VIEW discrete.cross_sections_view AS
      SELECT
          cs.xsection_id,
          cs.location_id,
          cs.datetime,

          CASE
              WHEN cs.use_calculated_values
              THEN COALESCE(calc.wetted_width_calculated_m, cs.wetted_width_m)
              ELSE COALESCE(cs.wetted_width_m, calc.wetted_width_calculated_m)
          END AS wetted_width_m,

          CASE
              WHEN cs.use_calculated_values
              THEN COALESCE(calc.total_area_calculated_m2, cs.total_area_m2)
              ELSE COALESCE(cs.total_area_m2, calc.total_area_calculated_m2)
          END AS total_area_m2,

          CASE
              WHEN cs.use_calculated_values
              THEN COALESCE(calc.net_area_calculated_m2, cs.net_area_m2)
              ELSE COALESCE(cs.net_area_m2, calc.net_area_calculated_m2)
          END AS net_area_m2,

          CASE
              WHEN cs.use_calculated_values
              THEN COALESCE(calc.avg_total_depth_calculated_m, cs.avg_total_depth_m)
              ELSE COALESCE(cs.avg_total_depth_m, calc.avg_total_depth_calculated_m)
          END AS avg_total_depth_m,

          CASE
              WHEN cs.use_calculated_values
              THEN COALESCE(calc.avg_velocity_calculated_m_s, cs.avg_velocity_m_s)
              ELSE COALESCE(cs.avg_velocity_m_s, calc.avg_velocity_calculated_m_s)
          END AS avg_velocity_m_s,

          CASE
              WHEN cs.use_calculated_values
              THEN COALESCE(calc.discharge_calculated_m3_s, cs.discharge_m3_s)
              ELSE COALESCE(cs.discharge_m3_s, calc.discharge_calculated_m3_s)
          END AS discharge_m3_s,

          CASE
              WHEN cs.use_calculated_values
              THEN COALESCE(calc.ice_avg_thickness_calculated_m, cs.ice_avg_thickness_m)
              ELSE COALESCE(cs.ice_avg_thickness_m, calc.ice_avg_thickness_calculated_m)
          END AS ice_avg_thickness_m,

          CASE
              WHEN cs.use_calculated_values
              THEN COALESCE(calc.ice_area_calculated_m2, cs.ice_area_m2)
              ELSE COALESCE(cs.ice_area_m2, calc.ice_area_calculated_m2)
          END AS ice_area_m2,

          CASE
              WHEN cs.use_calculated_values
              THEN COALESCE(calc.slush_avg_thickness_calculated_m, cs.slush_avg_thickness_m)
              ELSE COALESCE(cs.slush_avg_thickness_m, calc.slush_avg_thickness_calculated_m)
          END AS slush_avg_thickness_m,

          CASE
              WHEN cs.use_calculated_values
              THEN COALESCE(calc.slush_area_calculated_m2, cs.slush_area_m2)
              ELSE COALESCE(cs.slush_area_m2, calc.slush_area_calculated_m2)
          END AS slush_area_m2,

          cs.use_calculated_values,
          cs.source_system,
          cs.source_measurement_id,
          cs.note,
          cs.created,
          cs.modified,
          cs.created_by,
          cs.modified_by

      FROM discrete.cross_sections cs
      LEFT JOIN discrete.cross_sections_calculated calc
          ON cs.xsection_id = calc.xsection_id;
      "
    )

    #grant select permissions on tables to public role

    message("Adding SELECT permissions to tables...")

    DBI::dbExecute(
      con,
      "
      GRANT SELECT ON TABLE discrete.cross_sections TO public;
      "
    )

    DBI::dbExecute(
      con,
      "
      GRANT SELECT ON TABLE discrete.cross_section_verticals TO public;
      "
    )

    DBI::dbExecute(
      con,
      "
      GRANT SELECT ON TABLE discrete.cross_section_points TO public;
      "
    )

    # Add triggers to update modified_by and modified values for each table whenever a row is updated
    # Cross sections
    message("adding Modified and modified_by triggers...")

    DBI::dbExecute(
      con,
      "
      CREATE TRIGGER trg_user_audit_cross_sections
      BEFORE UPDATE ON discrete.cross_sections
      FOR EACH ROW
      EXECUTE FUNCTION user_modified();
      "
    )
    DBI::dbExecute(
      con,
      "
      CREATE TRIGGER update_modify_time_cross_sections
      BEFORE UPDATE ON discrete.cross_sections
      FOR EACH ROW
      EXECUTE FUNCTION update_modified();
      "
    )

    # Cross sections verticals
    DBI::dbExecute(
      con,
      "
      CREATE TRIGGER trg_user_audit_cross_section_verticals
      BEFORE UPDATE ON discrete.cross_section_verticals
      FOR EACH ROW
      EXECUTE FUNCTION user_modified();
      "
    )
    DBI::dbExecute(
      con,
      "
      CREATE TRIGGER update_modify_time_cross_section_verticals
      BEFORE UPDATE ON discrete.cross_section_verticals
      FOR EACH ROW
      EXECUTE FUNCTION update_modified();
      "
    )

    # Cross sections Points
    DBI::dbExecute(
      con,
      "
      CREATE TRIGGER trg_user_audit_cross_section_points
      BEFORE UPDATE ON discrete.cross_section_points
      FOR EACH ROW
      EXECUTE FUNCTION user_modified();
      "
    )
    DBI::dbExecute(
      con,
      "
      CREATE TRIGGER update_modify_time_cross_section_points
      BEFORE UPDATE ON discrete.cross_section_points
      FOR EACH ROW
      EXECUTE FUNCTION update_modified();
      "
    )

    # # TODO: set official patch number
    # DBI::dbExecute(
    #   con,
    #   "UPDATE information.version_info SET version = '53'
    #    WHERE item = 'Last patch number';"
    # )

    # DBI::dbExecute(
    #   con,
    #   paste0(
    #     "UPDATE information.version_info SET version = '",
    #     as.character(packageVersion('AquaCache')),
    #     "' WHERE item = 'AquaCache R package used for last patch';"
    #   )
    # )

    DBI::dbExecute(con, "COMMIT;")
    active <- FALSE

    # TODO: set official patch number
    message(
      "Patch 53 applied successfully. Cross-section, verticals, and points tables have been added to the discrete schema."
    )
  },
  error = function(e) {
    if (isTRUE(active)) {
      message("Error detected. Rolling back active transaction...")
      try(DBI::dbExecute(con, "ROLLBACK"), silent = TRUE)
    }
    stop(e)
  }
)
