# Patch 54: Adding cross-section, verticals, and points schema to aquacache database

check <- DBI::dbGetQuery(con, "SELECT SESSION_USER")

if (check$session_user != "postgres") {
  stop(
    "You do not have the necessary privileges for this patch. Connect as postgres user to make this work."
  )
}

# TODO: set official patch number
message(
  "Working on patch 54:  adding cross-section, verticals, and points tables to the discrete schema."
)

if (dbTransCheck(con)) {
  stop(
    "A transaction is already in progress. Please commit or rollback the current transaction before applying this patch."
  )
}

active <- FALSE
active <- dbTransBegin(con)

tryCatch(
  {
    # check for the following:
    # public.locations exists
    # information.version_info exists
    # cross section tables do not already exist
    check <- DBI::dbGetQuery(
      con,
      "SELECT
        to_regclass('public.locations') IS NOT NULL AS has_locations,
        to_regclass('information.version_info') IS NOT NULL AS has_version_info,
        to_regclass('discrete.cross_sections') IS NULL AS no_cross_sections,
        to_regclass('discrete.cross_section_verticals') IS NULL AS no_cross_section_verticals,
        to_regclass('discrete.cross_section_points') IS NULL AS no_cross_section_points"
    )

    if (
      !isTRUE(check$has_locations[[1]]) ||
        !isTRUE(check$has_version_info[[1]]) ||
        !isTRUE(check$no_cross_sections[[1]]) ||
        !isTRUE(check$no_cross_section_verticals[[1]]) ||
        !isTRUE(check$no_cross_section_points[[1]])
    ) {
      stop(
        "Patch 54 requires public.locations and information.version_info to exist, and cross-section tables must not already exist."
      )
    }

    # creating cross-sections table
    # Table: Cross Sections
    # Parent Table: public.locations
    # contains summary information for a cross section measurement.
    # one row = one single cross-section at one date

    message("Creating cross_sections table...")

    DBI::dbExecute(
      con,
      "
      CREATE TABLE discrete.cross_sections (
        xsection_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,

        location_id int4 NOT NULL,
        datetime timestamptz NOT NULL,

        wetted_width_m numeric NULL,
        total_area_m2 numeric NULL, 
        net_area_m2 numeric NULL, 
        avg_total_depth_m numeric NULL,    
        avg_velocity_m_s numeric NULL,
        discharge_m3_s numeric NULL,
        ice_avg_thickness_m numeric NULL,
        ice_area_m2 numeric NULL, -- new derived col, from verticals 
        slush_avg_thickness_m numeric NULL,
        slush_area_m2 numeric NULL,
        use_calculated_values boolean DEFAULT true NOT NULL,
        source_system text NULL, 
        source_measurement_id text NULL,
        note text NULL,
        created timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
        modified timestamptz NULL,
        created_by text DEFAULT CURRENT_USER NOT NULL,
        modified_by text NULL,

        CONSTRAINT cross_sections_pkey
            PRIMARY KEY (xsection_id),

        CONSTRAINT cross_sections_location_id_fkey
            FOREIGN KEY (location_id)
            REFERENCES public.locations(location_id)
            ON DELETE CASCADE
            ON UPDATE CASCADE,

        CONSTRAINT cross_sections_unique_location_datetime
           UNIQUE (location_id, datetime),

        CONSTRAINT cross_sections_unique_source UNIQUE (source_system, source_measurement_id)

      );
      "
    )

    # adding table and column comments for cross-sections table
    message("Adding comments to cross_sections table...")

    comments_cross_sections <- c(
      "COMMENT ON TABLE discrete.cross_sections IS 'Primary table for storing stream cross-section records. Links to locations and serves as parent table for cross_section_verticals.';",
      "COMMENT ON COLUMN discrete.cross_sections.wetted_width_m IS 'Manually entered wetted width of the stream cross-section, in metres. Used when vertical-level data are unavailable or should be overridden.';",
      "COMMENT ON COLUMN discrete.cross_sections.total_area_m2 IS 'Manually entered total cross-sectional area, including water, ice, and slush, in square metres.';",
      "COMMENT ON COLUMN discrete.cross_sections.net_area_m2 IS 'Manually entered area of the cross-section containing flowing water, excluding ice and slush, in square metres.';",
      "COMMENT ON COLUMN discrete.cross_sections.avg_total_depth_m IS 'Manually entered average total depth of the cross-section, in metres.';",
      "COMMENT ON COLUMN discrete.cross_sections.avg_velocity_m_s IS 'Manually entered average velocity of flowing water, in metres per second.';",
      "COMMENT ON COLUMN discrete.cross_sections.discharge_m3_s IS 'Manually entered discharge of flowing water, in cubic metres per second.';",
      "COMMENT ON COLUMN discrete.cross_sections.ice_avg_thickness_m IS 'Manually entered average ice thickness, in metres.';",
      "COMMENT ON COLUMN discrete.cross_sections.ice_area_m2 IS 'Manually entered cross-sectional area of ice, in square metres.';",
      "COMMENT ON COLUMN discrete.cross_sections.slush_avg_thickness_m IS 'Manually entered average slush ice thickness, in metres.';",
      "COMMENT ON COLUMN discrete.cross_sections.slush_area_m2 IS 'Manually entered cross-sectional area of slush ice, in square metres.';",
      "COMMENT ON COLUMN discrete.cross_sections.use_calculated_values IS 'When true, preferred-value views use calculated values where available before falling back to manual values. When false, manual values are preferred.';",
      "COMMENT ON COLUMN discrete.cross_sections.source_system IS 'Source system or import process that produced the record.';",
      "COMMENT ON COLUMN discrete.cross_sections.source_measurement_id IS 'Original source-system measurement identifier retained for traceability.';",
      "COMMENT ON COLUMN discrete.cross_sections.note IS 'Free-text note field for context that does not fit a structured column.';",
      "COMMENT ON COLUMN discrete.cross_sections.created IS 'Timestamp when the row was created.';",
      "COMMENT ON COLUMN discrete.cross_sections.modified IS 'Timestamp when the row was last updated.';",
      "COMMENT ON COLUMN discrete.cross_sections.created_by IS 'Database role recorded as the row creator.';",
      "COMMENT ON COLUMN discrete.cross_sections.modified_by IS 'Database role recorded as the last modifier.';"
    )

    for (comment_sql in comments_cross_sections) {
      DBI::dbExecute(con, comment_sql)
    }

    # creating verticals table
    # Table: Vertical
    # Parent Table: discrete.cross_sections
    # contains vertical level data (velocity, flowrate, icethickness, etc)
    # one row = one single vertical related to one cross section ID

    message("Creating cross_section_verticals table...")

    DBI::dbExecute(
      con,
      "
      CREATE TABLE discrete.cross_section_verticals (
        vertical_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,

        xsection_id int4 NOT NULL,
        measurement_time time NULL,

        distance_to_reference_m numeric NULL,
        distance_to_waterline_m numeric NOT NULL, 
        reference_bank text DEFAULT 'right' NOT NULL, 

        panel_flowing_water_depth_m numeric, 
        ice_thickness_m numeric NULL,
        water_surface_to_bottom_ice_m numeric NULL,
        slush_ice_thickness_m numeric NULL,
        
        panel_width_m numeric NULL,
        panel_area_m2 numeric NULL,

        panel_mean_velocity_m_s numeric NULL,
        panel_mean_velocity_calculated_m_s numeric NULL,
        panel_angle_of_flow_deg numeric NULL,
        panel_discharge_m3_s numeric NULL,
        panel_discharge_calculated_m3_s numeric, 

        use_calculated_values boolean DEFAULT true NOT NULL,

        source_vertical_id text NULL,
        note text NULL,

        created timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
        modified timestamptz NULL,
        created_by text DEFAULT CURRENT_USER NOT NULL,
        modified_by text NULL,

        CONSTRAINT cross_section_verticals_pkey
            PRIMARY KEY (vertical_id),

        CONSTRAINT cross_section_verticals_xsection_id_fkey
            FOREIGN KEY (xsection_id)
            REFERENCES discrete.cross_sections(xsection_id)
            ON DELETE CASCADE
            ON UPDATE CASCADE,

        CONSTRAINT cross_section_verticals_reference_bank_check
            CHECK (reference_bank IN ('left', 'right')), 

            CONSTRAINT cross_section_verticals_unique_distance_reference
            UNIQUE (
                xsection_id,
                distance_to_reference_m
            ),
            
            CONSTRAINT cross_section_verticals_unique_distance_waterline
            UNIQUE NULLS NOT DISTINCT (
                xsection_id,
                distance_to_waterline_m
            ),
                            
        CONSTRAINT cross_section_verticals_unique_source
            UNIQUE (xsection_id, source_vertical_id)

      );
      "
    )

    # adding table and column comments for verticals table
    message("Adding comments to cross_section_verticals table...")

    comments_cross_section_verticals <- c(
      "COMMENT ON TABLE discrete.cross_section_verticals IS 'Secondary table for storing vertical panel measurements within a stream cross-section. Links to discrete.cross_sections via xsection_id and serves as the parent table for discrete.cross_section_points. Each row represents one vertical panel and stores panel geometry, water, ice, slush, and manually entered hydraulic measurements.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.distance_to_reference_m IS 'Distance from the survey reference point used during measurement. Preserved primarily for compatibility with legacy Ice Thickness DB records.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.distance_to_waterline_m IS 'Horizontal distance from the centre of the panel to the shoreline reference, in metres.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.reference_bank IS 'Bank from which horizontal distances are measured. Defaults to right bank.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.panel_flowing_water_depth_m IS 'Depth of the flowing water column at the panel location, measured from the stream bed to the water surface, in metres.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.ice_thickness_m IS 'Thickness of ice at the panel location, in metres.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.water_surface_to_bottom_ice_m IS 'Distance between the water surface and the underside of the ice layer, in metres.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.slush_ice_thickness_m IS 'Thickness of slush ice at the panel location, in metres.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.panel_width_m IS 'Width represented by the vertical panel, in metres.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.panel_area_m2 IS 'Manually entered area of flowing water represented by the panel, in square metres.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.panel_mean_velocity_m_s IS 'Manually entered mean velocity of flowing water through the panel, in metres per second.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.panel_angle_of_flow_deg IS 'Angle of flow relative to the panel normal, in degrees.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.panel_discharge_m3_s IS 'Manually entered discharge through the panel, in cubic metres per second.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.use_calculated_values IS 'When true, preferred-value views use calculated values where available before falling back to manually entered values. When false, manual values are preferred.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.source_vertical_id IS 'Original identifier from the legacy source system. Retained for migration traceability.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.note IS 'Free-text note field for context that does not fit a structured column.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.created IS 'Timestamp when the row was created.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.modified IS 'Timestamp when the row was last updated.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.created_by IS 'Database role recorded as the row creator.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals.modified_by IS 'Database role recorded as the last modifier.';"
    )

    for (comment_sql in comments_cross_section_verticals) {
      DBI::dbExecute(con, comment_sql)
    }

    # creating points table
    # Table: Points
    # Parent Table: discrete.cross_section_verticals
    # contains points level data (point depth, velocity)
    # one row = one single point related to one vertical ID

    message("Creating cross_section_points table...")

    DBI::dbExecute(
      con,
      "
      CREATE TABLE discrete.cross_section_points (
        point_id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,

        vertical_id int4 NOT NULL,

        rel_position_on_water_panel numeric NOT NULL CHECK (rel_position_on_water_panel > 0 AND rel_position_on_water_panel < 1),
        depth_in_moving_water_m numeric NULL,

        velocity_m_s numeric NOT NULL,

        note text NULL,

        created timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
        modified timestamptz NULL,
        created_by text DEFAULT CURRENT_USER NOT NULL,
        modified_by text NULL,

        CONSTRAINT cross_section_points_pkey
            PRIMARY KEY (point_id),

        CONSTRAINT cross_section_points_vertical_id_fkey
            FOREIGN KEY (vertical_id)
            REFERENCES discrete.cross_section_verticals(vertical_id)
            ON DELETE CASCADE
            ON UPDATE CASCADE
        
      );
      "
    )

    # adding table and column comments for points table
    message("Adding comments to cross_section_points table...")

    comments_cross_section_points <- c(
      "COMMENT ON TABLE discrete.cross_section_points IS 'Tertiary table storing point measurements within a vertical panel. Links to discrete.cross_section_verticals via vertical_id. Each row represents a single velocity measurement collected at a specific location within the panel.';",
      "COMMENT ON COLUMN discrete.cross_section_points.rel_position_on_water_panel IS 'Relative position of the measurement point within the panel, expressed as a proportion between 0 and 1, with 0 being the surface of the water.';",
      "COMMENT ON COLUMN discrete.cross_section_points.depth_in_moving_water_m IS 'Depth of the velocity measurement within the flowing water column, in metres with 0 being the surface of the water.';",
      "COMMENT ON COLUMN discrete.cross_section_points.velocity_m_s IS 'Velocity of flowing water measured at the point location, in metres per second.';",
      "COMMENT ON COLUMN discrete.cross_section_points.note IS 'Free-text note field for context that does not fit a structured column.';",
      "COMMENT ON COLUMN discrete.cross_section_points.created IS 'Timestamp when the row was created.';",
      "COMMENT ON COLUMN discrete.cross_section_points.modified IS 'Timestamp when the row was last updated.';",
      "COMMENT ON COLUMN discrete.cross_section_points.created_by IS 'Database role recorded as the row creator.';",
      "COMMENT ON COLUMN discrete.cross_section_points.modified_by IS 'Database role recorded as the last modifier.';"
    )

    for (comment_sql in comments_cross_section_points) {
      DBI::dbExecute(con, comment_sql)
    }

    # Creating the following 4 Views
    # 1 cross_section_verticals_calculated: view of calculated fields for verticals table
    # 2 cross_section_verticals_view: view coalescing calculated & manual fields for verticals table
    # 3 cross_sections_calculated: view of calculated fields for cross section table
    # 4 cross_sections_view: view coalescing calculated & manuel fields for cross section table

    # VIEW 1: Create view of values calculated from verticals table
    message(
      "Creating view of calculated fields for cross section verticals table..."
    )

    DBI::dbExecute(
      con,
      "
      CREATE VIEW discrete.cross_section_verticals_calculated AS
      SELECT
          v.vertical_id,

          CASE
              WHEN v.panel_width_m IS NOT NULL
              AND v.panel_flowing_water_depth_m IS NOT NULL
              THEN v.panel_width_m * v.panel_flowing_water_depth_m
              ELSE NULL
          END AS panel_area_calculated_m2,

          AVG(p.velocity_m_s) AS panel_mean_velocity_calculated_m_s,

          CASE
              WHEN v.panel_width_m IS NOT NULL
              AND v.panel_flowing_water_depth_m IS NOT NULL
              AND AVG(p.velocity_m_s) IS NOT NULL
              THEN
                  (v.panel_width_m * v.panel_flowing_water_depth_m)
                  * AVG(p.velocity_m_s)
              ELSE NULL
          END AS panel_discharge_calculated_m3_s

      FROM discrete.cross_section_verticals v
      LEFT JOIN discrete.cross_section_points p
          ON v.vertical_id = p.vertical_id
      GROUP BY
          v.vertical_id,
          v.panel_width_m,
          v.panel_flowing_water_depth_m;
      "
    )

    comments_cross_sections_verticals_calculated <- c(
      "COMMENT ON VIEW discrete.cross_section_verticals_calculated IS 'View containing hydraulic properties calculated from point-level measurements stored in discrete.cross_section_points. Values are recalculated dynamically and are not stored in the underlying tables.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals_calculated.panel_area_calculated_m2 IS 'Calculated panel area, equal to panel_width_m × panel_flowing_water_depth_m.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals_calculated.panel_mean_velocity_calculated_m_s IS 'Calculated mean panel velocity, computed as the average of all point velocities within the panel.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals_calculated.panel_discharge_calculated_m3_s IS 'Calculated panel discharge, equal to calculated panel area × calculated mean panel velocity.';"
    )

    for (comment_sql in comments_cross_sections_verticals_calculated) {
      DBI::dbExecute(con, comment_sql)
    }

    # View 2: creating view for verticals table coalescing manual/calculated fields
    message(
      "Creating view of preferred values for cross section verticals table..."
    )

    DBI::dbExecute(
      con,
      "
      CREATE VIEW discrete.cross_section_verticals_view AS
      SELECT
          v.vertical_id,
          v.xsection_id,
          v.measurement_time,
          v.distance_to_reference_m,
          v.distance_to_waterline_m,
          v.reference_bank,

          v.panel_flowing_water_depth_m,
          v.ice_thickness_m,
          v.water_surface_to_bottom_ice_m,
          v.slush_ice_thickness_m,
          v.panel_width_m,
          
          CASE
              WHEN v.use_calculated_values
              THEN COALESCE(vc.panel_area_calculated_m2, v.panel_area_m2)
              ELSE COALESCE(v.panel_area_m2, vc.panel_area_calculated_m2)
          END AS panel_area_m2,

          CASE
              WHEN v.use_calculated_values
              THEN COALESCE(vc.panel_mean_velocity_calculated_m_s, v.panel_mean_velocity_m_s)
              ELSE COALESCE(v.panel_mean_velocity_m_s, vc.panel_mean_velocity_calculated_m_s)
          END AS panel_mean_velocity_m_s,

          v.panel_angle_of_flow_deg,

          CASE
              WHEN v.use_calculated_values
              THEN COALESCE(vc.panel_discharge_calculated_m3_s, v.panel_discharge_m3_s)
              ELSE COALESCE(v.panel_discharge_m3_s, vc.panel_discharge_calculated_m3_s)
          END AS panel_discharge_m3_s,

          v.source_vertical_id,
          v.note,
          v.created,
          v.modified,
          v.created_by,
          v.modified_by
      FROM discrete.cross_section_verticals v
      LEFT JOIN discrete.cross_section_verticals_calculated vc
          ON v.vertical_id = vc.vertical_id;
      "
    )

    comments_cross_sections_verticals_view <- c(
      "COMMENT ON VIEW discrete.cross_section_verticals_view IS 'User-facing view of cross-section vertical measurements. Presents manually entered or calculated hydraulic values according to the use_calculated_values flag while exposing all remaining panel information unchanged.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals_view.panel_area_m2 IS 'Preferred panel area. Returns the calculated value when use_calculated_values is TRUE and available; otherwise returns the manually entered value.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals_view.panel_mean_velocity_m_s IS 'Preferred mean panel velocity. Returns the calculated value when use_calculated_values is TRUE and available; otherwise returns the manually entered value.';",
      "COMMENT ON COLUMN discrete.cross_section_verticals_view.panel_discharge_m3_s IS 'Preferred panel discharge. Returns the calculated value when use_calculated_values is TRUE and available; otherwise returns the manually entered value.';"
    )

    for (comment_sql in comments_cross_sections_verticals_view) {
      DBI::dbExecute(con, comment_sql)
    }

    # VIEW 3: Create view of values calculated from verticals table
    #note, cross section calculated values use vertical preferred-value View rather than cross_section_verticals table, to preserve manual-calculated value preference
    message("Creating view of calculated fields for cross section table...")
    DBI::dbExecute(
      con,
      "
      CREATE VIEW discrete.cross_sections_calculated AS
      SELECT
        cs.xsection_id,

        SUM(v.panel_width_m) AS wetted_width_calculated_m,

        SUM(v.panel_area_m2) AS net_area_calculated_m2,

        CASE
          WHEN SUM(v.panel_area_m2) IS NOT NULL
            OR SUM(v.panel_width_m * v.ice_thickness_m) IS NOT NULL
            OR SUM(v.panel_width_m * v.slush_ice_thickness_m) IS NOT NULL
          THEN
              COALESCE(SUM(v.panel_area_m2), 0)
            + COALESCE(SUM(v.panel_width_m * v.ice_thickness_m), 0)
            + COALESCE(SUM(v.panel_width_m * v.slush_ice_thickness_m), 0)
          ELSE NULL
        END AS total_area_calculated_m2,

        AVG(v.panel_flowing_water_depth_m) AS avg_total_depth_calculated_m,

        AVG(v.panel_mean_velocity_m_s) AS avg_velocity_calculated_m_s,

        SUM(v.panel_discharge_m3_s) AS discharge_calculated_m3_s,

        AVG(v.ice_thickness_m) AS ice_avg_thickness_calculated_m,

        SUM(v.panel_width_m * v.ice_thickness_m) AS ice_area_calculated_m2,

        AVG(v.slush_ice_thickness_m) AS slush_avg_thickness_calculated_m,

        SUM(v.panel_width_m * v.slush_ice_thickness_m) AS slush_area_calculated_m2

      FROM discrete.cross_sections cs
      LEFT JOIN discrete.cross_section_verticals_view v
        ON cs.xsection_id = v.xsection_id
      
      GROUP BY cs.xsection_id;
      "
    )

    comments_cross_section_calculated <- c(
      "COMMENT ON VIEW discrete.cross_sections_calculated IS 'View containing cross-section summary statistics calculated dynamically from discrete.cross_section_verticals_view. Values are recalculated from available vertical measurements and are not stored in the underlying tables.';",
      "COMMENT ON COLUMN discrete.cross_sections_calculated.wetted_width_calculated_m IS 'Calculated wetted width of the cross section.';",
      "COMMENT ON COLUMN discrete.cross_sections_calculated.net_area_calculated_m2 IS 'Calculated flowing-water area of the cross section.';",
      "COMMENT ON COLUMN discrete.cross_sections_calculated.total_area_calculated_m2 IS 'Calculated total cross-sectional area, including flowing water, ice, and slush.';",
      "COMMENT ON COLUMN discrete.cross_sections_calculated.avg_total_depth_calculated_m IS 'Calculated mean flowing-water depth across all verticals.';",
      "COMMENT ON COLUMN discrete.cross_sections_calculated.avg_velocity_calculated_m_s IS 'Calculated mean flowing-water velocity across all verticals.';",
      "COMMENT ON COLUMN discrete.cross_sections_calculated.discharge_calculated_m3_s IS 'Calculated total discharge of the cross section.';",
      "COMMENT ON COLUMN discrete.cross_sections_calculated.ice_avg_thickness_calculated_m IS 'Calculated mean ice thickness across all verticals.';",
      "COMMENT ON COLUMN discrete.cross_sections_calculated.ice_area_calculated_m2 IS 'Calculated cross-sectional area occupied by ice.';",
      "COMMENT ON COLUMN discrete.cross_sections_calculated.slush_avg_thickness_calculated_m IS 'Calculated mean slush thickness across all verticals.';",
      "COMMENT ON COLUMN discrete.cross_sections_calculated.slush_area_calculated_m2 IS 'Calculated cross-sectional area occupied by slush.';"
    )

    for (comment_sql in comments_cross_section_calculated) {
      DBI::dbExecute(con, comment_sql)
    }

    # VIEW 4: Create view of cross section table coalescing manual/calculated fields
    message("Creating view of preferred values for cross section table...")

    DBI::dbExecute(
      con,
      "
      CREATE VIEW discrete.cross_sections_view AS
      SELECT
          cs.xsection_id,
          cs.location_id,
          cs.datetime,

          CASE
              WHEN cs.use_calculated_values
              THEN COALESCE(calc.wetted_width_calculated_m, cs.wetted_width_m)
              ELSE COALESCE(cs.wetted_width_m, calc.wetted_width_calculated_m)
          END AS wetted_width_m,

          CASE
              WHEN cs.use_calculated_values
              THEN COALESCE(calc.total_area_calculated_m2, cs.total_area_m2)
              ELSE COALESCE(cs.total_area_m2, calc.total_area_calculated_m2)
          END AS total_area_m2,

          CASE
              WHEN cs.use_calculated_values
              THEN COALESCE(calc.net_area_calculated_m2, cs.net_area_m2)
              ELSE COALESCE(cs.net_area_m2, calc.net_area_calculated_m2)
          END AS net_area_m2,

          CASE
              WHEN cs.use_calculated_values
              THEN COALESCE(calc.avg_total_depth_calculated_m, cs.avg_total_depth_m)
              ELSE COALESCE(cs.avg_total_depth_m, calc.avg_total_depth_calculated_m)
          END AS avg_total_depth_m,

          CASE
              WHEN cs.use_calculated_values
              THEN COALESCE(calc.avg_velocity_calculated_m_s, cs.avg_velocity_m_s)
              ELSE COALESCE(cs.avg_velocity_m_s, calc.avg_velocity_calculated_m_s)
          END AS avg_velocity_m_s,

          CASE
              WHEN cs.use_calculated_values
              THEN COALESCE(calc.discharge_calculated_m3_s, cs.discharge_m3_s)
              ELSE COALESCE(cs.discharge_m3_s, calc.discharge_calculated_m3_s)
          END AS discharge_m3_s,

          CASE
              WHEN cs.use_calculated_values
              THEN COALESCE(calc.ice_avg_thickness_calculated_m, cs.ice_avg_thickness_m)
              ELSE COALESCE(cs.ice_avg_thickness_m, calc.ice_avg_thickness_calculated_m)
          END AS ice_avg_thickness_m,

          CASE
              WHEN cs.use_calculated_values
              THEN COALESCE(calc.ice_area_calculated_m2, cs.ice_area_m2)
              ELSE COALESCE(cs.ice_area_m2, calc.ice_area_calculated_m2)
          END AS ice_area_m2,

          CASE
              WHEN cs.use_calculated_values
              THEN COALESCE(calc.slush_avg_thickness_calculated_m, cs.slush_avg_thickness_m)
              ELSE COALESCE(cs.slush_avg_thickness_m, calc.slush_avg_thickness_calculated_m)
          END AS slush_avg_thickness_m,

          CASE
              WHEN cs.use_calculated_values
              THEN COALESCE(calc.slush_area_calculated_m2, cs.slush_area_m2)
              ELSE COALESCE(cs.slush_area_m2, calc.slush_area_calculated_m2)
          END AS slush_area_m2,

          cs.use_calculated_values,
          cs.source_system,
          cs.source_measurement_id,
          cs.note,
          cs.created,
          cs.modified,
          cs.created_by,
          cs.modified_by

      FROM discrete.cross_sections cs
      LEFT JOIN discrete.cross_sections_calculated calc
          ON cs.xsection_id = calc.xsection_id;
      "
    )

    comments_cross_section_view <- c(
      "COMMENT ON VIEW discrete.cross_sections_view IS 'User-facing view of cross-section measurements. Presents manually entered or calculated summary values according to the use_calculated_values flag while exposing all remaining cross-section information unchanged.';",
      "COMMENT ON COLUMN discrete.cross_sections_view.wetted_width_m IS 'Preferred wetted width. Returns the calculated value when use_calculated_values is TRUE and available; otherwise returns the manually entered value.';",
      "COMMENT ON COLUMN discrete.cross_sections_view.total_area_m2 IS 'Preferred total cross-sectional area. Returns the calculated value when use_calculated_values is TRUE and available; otherwise returns the manually entered value.';",
      "COMMENT ON COLUMN discrete.cross_sections_view.net_area_m2 IS 'Preferred flowing-water area. Returns the calculated value when use_calculated_values is TRUE and available; otherwise returns the manually entered value.';",
      "COMMENT ON COLUMN discrete.cross_sections_view.avg_total_depth_m IS 'Preferred average flowing-water depth. Returns the calculated value when use_calculated_values is TRUE and available; otherwise returns the manually entered value.';",
      "COMMENT ON COLUMN discrete.cross_sections_view.avg_velocity_m_s IS 'Preferred average flowing-water velocity. Returns the calculated value when use_calculated_values is TRUE and available; otherwise returns the manually entered value.';",
      "COMMENT ON COLUMN discrete.cross_sections_view.discharge_m3_s IS 'Preferred discharge. Returns the calculated value when use_calculated_values is TRUE and available; otherwise returns the manually entered value.';",
      "COMMENT ON COLUMN discrete.cross_sections_view.ice_avg_thickness_m IS 'Preferred average ice thickness. Returns the calculated value when use_calculated_values is TRUE and available; otherwise returns the manually entered value.';",
      "COMMENT ON COLUMN discrete.cross_sections_view.ice_area_m2 IS 'Preferred ice area. Returns the calculated value when use_calculated_values is TRUE and available; otherwise returns the manually entered value.';",
      "COMMENT ON COLUMN discrete.cross_sections_view.slush_avg_thickness_m IS 'Preferred average slush thickness. Returns the calculated value when use_calculated_values is TRUE and available; otherwise returns the manually entered value.';",
      "COMMENT ON COLUMN discrete.cross_sections_view.slush_area_m2 IS 'Preferred slush area. Returns the calculated value when use_calculated_values is TRUE and available; otherwise returns the manually entered value.';"
    )

    for (comment_sql in comments_cross_section_view) {
      DBI::dbExecute(con, comment_sql)
    }

    #grant select permissions on tables to public role

    message("Adding SELECT permissions to tables...")

    DBI::dbExecute(
      con,
      "
      GRANT SELECT ON TABLE discrete.cross_sections TO public;
      "
    )

    DBI::dbExecute(
      con,
      "
      GRANT SELECT ON TABLE discrete.cross_section_verticals TO public;
      "
    )

    DBI::dbExecute(
      con,
      "
      GRANT SELECT ON TABLE discrete.cross_section_points TO public;
      "
    )

    DBI::dbExecute(
      con,
      "
          GRANT SELECT ON VIEW discrete.cross_section_verticals_view TO public;
          "
    )

    DBI::dbExecute(
      con,
      "
      GRANT SELECT ON VIEW discrete.cross_section_view TO public;
      "
    )

    q_literal <- function(x) {
      as.character(DBI::dbQuoteString(con, x))
    }
    q_role <- function(x) {
      as.character(DBI::dbQuoteIdentifier(con, x))
    }
    sql_text_array <- function(x) {
      if (length(x) == 0L) {
        return("ARRAY[]::text[]")
      }

      sprintf(
        "ARRAY[%s]::text[]",
        paste(vapply(x, q_literal, character(1)), collapse = ", ")
      )
    }

    existing_roles <- DBI::dbGetQuery(
      con,
      "SELECT rolname FROM pg_roles"
    )$rolname

    get_roles_with_reference_privileges <- function(
      reference_table,

      privileges,

      always_include = character()
    ) {
      roles <- DBI::dbGetQuery(
        con,

        sprintf(
          "

          SELECT x.role_name

          FROM (

            SELECT r.rolname AS role_name

            FROM pg_roles AS r

            WHERE r.rolcanlogin = false

              AND r.rolname NOT IN (

                'public',

                'pg_read_all_data',

                'pg_write_all_data'

              )

              AND NOT EXISTS (

                SELECT 1

                FROM unnest(%s) AS p(privilege_name)

                WHERE NOT has_table_privilege(

                  r.oid,

                  %s::regclass,

                  p.privilege_name

                )

              )
 
            UNION
 
            SELECT r.rolname AS role_name

            FROM pg_roles AS r

            WHERE r.rolname = ANY(%s)

          ) AS x

          ORDER BY x.role_name;",

          sql_text_array(privileges),

          q_literal(reference_table),

          sql_text_array(always_include)
        )
      )$role_name

      intersect(unique(roles), existing_roles)
    }

    criteria_editor_roles <- get_roles_with_reference_privileges(
      "public.locations",

      c("INSERT", "UPDATE", "DELETE"),

      "admin"
    )

    grant_table_privileges <- function(table_names, privileges, roles) {
      if (length(roles) == 0L) {
        return(invisible(NULL))
      }

      for (role_name in roles) {
        DBI::dbExecute(
          con,

          sprintf(
            "GRANT %s ON TABLE %s TO %s;",

            privileges,

            paste(table_names, collapse = ", "),

            q_role(role_name)
          )
        )
      }

      invisible(NULL)
    }

    grant_table_privileges(
      "cross_sections, cross_section_verticals, cross_section_points",

      "SELECT, INSERT, UPDATE, DELETE",

      criteria_editor_roles
    )

    # Add triggers to update modified_by and modified values for each table whenever a row is updated
    # Cross sections
    message("adding Modified and modified_by triggers...")

    DBI::dbExecute(
      con,
      "
      CREATE TRIGGER trg_user_audit_cross_sections
      BEFORE UPDATE ON discrete.cross_sections
      FOR EACH ROW
      EXECUTE FUNCTION user_modified();
      "
    )
    DBI::dbExecute(
      con,
      "
      CREATE TRIGGER update_modify_time_cross_sections
      BEFORE UPDATE ON discrete.cross_sections
      FOR EACH ROW
      EXECUTE FUNCTION update_modified();
      "
    )

    # Cross sections verticals
    DBI::dbExecute(
      con,
      "
      CREATE TRIGGER trg_user_audit_cross_section_verticals
      BEFORE UPDATE ON discrete.cross_section_verticals
      FOR EACH ROW
      EXECUTE FUNCTION user_modified();
      "
    )
    DBI::dbExecute(
      con,
      "
      CREATE TRIGGER update_modify_time_cross_section_verticals
      BEFORE UPDATE ON discrete.cross_section_verticals
      FOR EACH ROW
      EXECUTE FUNCTION update_modified();
      "
    )

    # Cross sections Points
    DBI::dbExecute(
      con,
      "
      CREATE TRIGGER trg_user_audit_cross_section_points
      BEFORE UPDATE ON discrete.cross_section_points
      FOR EACH ROW
      EXECUTE FUNCTION user_modified();
      "
    )
    DBI::dbExecute(
      con,
      "
      CREATE TRIGGER update_modify_time_cross_section_points
      BEFORE UPDATE ON discrete.cross_section_points
      FOR EACH ROW
      EXECUTE FUNCTION update_modified();
      "
    )

    apply_parent_visibility_policy <- function(
      schema_name,
      table_name,
      using_sql
    ) {
      q_table <- function(schema_name, table_name) {
        paste(
          as.character(DBI::dbQuoteIdentifier(con, schema_name)),
          as.character(DBI::dbQuoteIdentifier(con, table_name)),
          sep = "."
        )
      }

      qual <- q_table(schema_name, table_name)

      DBI::dbExecute(
        con,
        sprintf("ALTER TABLE %s ENABLE ROW LEVEL SECURITY", qual)
      )

      DBI::dbExecute(
        con,
        sprintf(
          "DROP POLICY IF EXISTS parent_visibility_restrict ON %s",
          qual
        )
      )
      DBI::dbExecute(
        con,
        sprintf(
          "CREATE POLICY parent_visibility_restrict ON %s AS RESTRICTIVE FOR SELECT USING (%s)",
          qual,
          using_sql
        )
      )

      DBI::dbExecute(
        con,
        sprintf(
          "DROP POLICY IF EXISTS parent_visibility_restrict_insert ON %s",
          qual
        )
      )
      DBI::dbExecute(
        con,
        sprintf(
          "CREATE POLICY parent_visibility_restrict_insert ON %s AS RESTRICTIVE FOR INSERT WITH CHECK (%s)",
          qual,
          using_sql
        )
      )

      DBI::dbExecute(
        con,
        sprintf(
          "DROP POLICY IF EXISTS parent_visibility_restrict_update ON %s",
          qual
        )
      )
      DBI::dbExecute(
        con,
        sprintf(
          "CREATE POLICY parent_visibility_restrict_update ON %s AS RESTRICTIVE FOR UPDATE USING (%s) WITH CHECK (%s)",
          qual,
          using_sql,
          using_sql
        )
      )

      DBI::dbExecute(
        con,
        sprintf(
          "DROP POLICY IF EXISTS parent_visibility_restrict_delete ON %s",
          qual
        )
      )
      DBI::dbExecute(
        con,
        sprintf(
          "CREATE POLICY parent_visibility_restrict_delete ON %s AS RESTRICTIVE FOR DELETE USING (%s)",
          qual,
          using_sql
        )
      )

      DBI::dbExecute(
        con,
        sprintf(
          "DROP POLICY IF EXISTS parent_visibility_allow_select ON %s",
          qual
        )
      )
      DBI::dbExecute(
        con,
        sprintf(
          "CREATE POLICY parent_visibility_allow_select ON %s FOR SELECT USING (true)",
          qual
        )
      )

      DBI::dbExecute(
        con,
        sprintf(
          "DROP POLICY IF EXISTS parent_visibility_allow_insert ON %s",
          qual
        )
      )
      DBI::dbExecute(
        con,
        sprintf(
          "CREATE POLICY parent_visibility_allow_insert ON %s FOR INSERT WITH CHECK (true)",
          qual
        )
      )

      DBI::dbExecute(
        con,
        sprintf(
          "DROP POLICY IF EXISTS parent_visibility_allow_update ON %s",
          qual
        )
      )
      DBI::dbExecute(
        con,
        sprintf(
          "CREATE POLICY parent_visibility_allow_update ON %s FOR UPDATE USING (true) WITH CHECK (true)",
          qual
        )
      )

      DBI::dbExecute(
        con,
        sprintf(
          "DROP POLICY IF EXISTS parent_visibility_allow_delete ON %s",
          qual
        )
      )
      DBI::dbExecute(
        con,
        sprintf(
          "CREATE POLICY parent_visibility_allow_delete ON %s FOR DELETE USING (true)",
          qual
        )
      )
    }

    visible_timeseries_sql <- function(child_table, child_column) {
      sprintf(
        "%1$s IS NULL OR EXISTS (
           SELECT 1
           FROM public.locations l
           WHERE l.location_id = %2$s.%1$s
         )",
        child_column,
        child_table
      )
    }

    apply_parent_visibility_policy(
      "discrete",
      "cross_sections",
      visible_timeseries_sql("cross_sections", "location_id")
    )

    # update version to reflect patch number
    DBI::dbExecute(
      con,
      "UPDATE information.version_info SET version = '54'
       WHERE item = 'Last patch number';"
    )

    DBI::dbExecute(
      con,
      paste0(
        "UPDATE information.version_info SET version = '",
        as.character(packageVersion('AquaCache')),
        "' WHERE item = 'AquaCache R package used for last patch';"
      )
    )

    DBI::dbExecute(con, "COMMIT;")
    active <- FALSE

    message(
      "Patch 54 applied successfully. Cross-section, verticals, and points tables have been added to the discrete schema."
    )
  },
  error = function(e) {
    if (isTRUE(active)) {
      message("Error detected. Rolling back active transaction...")
      try(DBI::dbExecute(con, "ROLLBACK"), silent = TRUE)
    }
    stop(e)
  }
)
