# Patch 38

# Initial checks #################
# Ensure the user is postgres as this patch requires it
check <- DBI::dbGetQuery(con, "SELECT SESSION_USER")

if (check$session_user != "postgres") {
  stop(
    "You do not have the necessary privileges for this patch. Connect as postgres user to make this work."
  )
}

message(
  "Working on Patch 38. Changes are being made within a transaction, so if something goes wrong, the database will be rolled back to its previous state (but you have a backup, right?)."
)

# Begin a transaction
message("Starting transaction...")
warning(
  "\nThis patch can take a long time to run as it updates all existing continuous measurements to have stable row identifiers. Be patient, and consider running this during a maintenance window if you have a large dataset.\n"
)

check <- dbTransCheck(con) # Check if a transaction is already in progress
if (check) {
  stop(
    "A transaction is already in progress. Please commit or rollback the current transaction before applying this patch."
  )
}
active <- dbTransBegin(con)

tryCatch(
  {
    # Basic sanity checks ###################################################
    check <- DBI::dbGetQuery(
      con,
      paste(
        "SELECT",
        "to_regclass('audit.general_log') IS NOT NULL AS has_general_log,",
        "to_regclass('audit.measurements_continuous_log') IS NOT NULL AS has_measurements_continuous_log,",
        "to_regclass('audit.measurements_calculated_daily_log') IS NOT NULL AS has_measurements_calculated_daily_log,",
        "to_regclass('continuous.measurements_continuous') IS NOT NULL AS has_measurements_continuous,",
        "to_regclass('continuous.measurements_calculated_daily') IS NOT NULL AS has_measurements_calculated_daily,",
        "to_regclass('continuous.corrections') IS NOT NULL AS has_corrections,",
        "to_regclass('continuous.correction_types') IS NOT NULL AS has_correction_types,",
        "to_regclass('continuous.timeseries') IS NOT NULL AS has_timeseries"
      )
    )

    if (
      !isTRUE(check$has_general_log[[1]]) ||
        !isTRUE(check$has_measurements_continuous_log[[1]]) ||
        !isTRUE(check$has_measurements_calculated_daily_log[[1]]) ||
        !isTRUE(check$has_measurements_continuous[[1]]) ||
        !isTRUE(check$has_measurements_calculated_daily[[1]]) ||
        !isTRUE(check$has_corrections[[1]]) ||
        !isTRUE(check$has_correction_types[[1]]) ||
        !isTRUE(check$has_timeseries[[1]])
    ) {
      stop(
        paste(
          "Patch 38 requires the patch 37 audit tables plus",
          "continuous.measurements_continuous,",
          "continuous.measurements_calculated_daily,",
          "continuous.corrections,",
          "continuous.correction_types, and",
          "continuous.timeseries to already exist."
        )
      )
    }

    audit_roles <- DBI::dbGetQuery(con, "SELECT rolname FROM pg_roles;")$rolname
    audit_editor_roles <- intersect(
      c("yg_editor_group", "yg_editor"),
      audit_roles
    )
    audit_reader_roles <- intersect(
      c("yg_reader_group", "yg_reader"),
      audit_roles
    )
    historical_function_roles <- unique(c(
      audit_editor_roles,
      audit_reader_roles
    ))

    # Upgrade path for patch 37 generic audit rows ##########################
    DBI::dbExecute(
      con,
      "ALTER TABLE audit.general_log
       ADD COLUMN IF NOT EXISTS row_created TIMESTAMPTZ;"
    )
    DBI::dbExecute(
      con,
      "ALTER TABLE audit.general_log
       ADD COLUMN IF NOT EXISTS row_modified TIMESTAMPTZ;"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON COLUMN audit.general_log.row_created IS
       'Value of the source row created column, when present, captured separately so historical reconstruction can determine whether a row existed at a requested as-of timestamp.';"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON COLUMN audit.general_log.row_modified IS
       'Value of the source row modified column, when present, captured separately so historical reconstruction can recover the last modification timestamp without polluting changed_fields.';"
    )

    # Stable row identity for measurement history ##########################
    DBI::dbExecute(
      con,
      "DROP TRIGGER IF EXISTS audit_measurements_continuous_trigger
       ON continuous.measurements_continuous;"
    )
    DBI::dbExecute(
      con,
      "DROP TRIGGER IF EXISTS audit_measurements_calculated_daily_trigger
       ON continuous.measurements_calculated_daily;"
    )

    message(
      "Adding stable row identifiers to measurements_continuous and measurements_calculated_daily."
    )
    DBI::dbExecute(
      con,
      "ALTER TABLE continuous.measurements_continuous
       ADD COLUMN IF NOT EXISTS measurement_row_id BIGINT
       GENERATED BY DEFAULT AS IDENTITY;"
    )
    DBI::dbExecute(
      con,
      "ALTER TABLE continuous.measurements_calculated_daily
       ADD COLUMN IF NOT EXISTS measurement_row_id BIGINT
       GENERATED BY DEFAULT AS IDENTITY;"
    )
    DBI::dbExecute(
      con,
      "ALTER TABLE audit.measurements_continuous_log
       ADD COLUMN IF NOT EXISTS measurement_row_id BIGINT;"
    )
    DBI::dbExecute(
      con,
      "ALTER TABLE audit.measurements_calculated_daily_log
       ADD COLUMN IF NOT EXISTS measurement_row_id BIGINT;"
    )

    message(
      "Populating stable row identifiers for existing measurements. This may take a **very** long while depending on the size of your dataset, but it only needs to be done once!"
    )
    DBI::dbExecute(
      con,
      "UPDATE continuous.measurements_continuous
       SET measurement_row_id = DEFAULT
       WHERE measurement_row_id IS NULL;"
    )
    message("Stable row identifiers added to measurements_continuous.")
    DBI::dbExecute(
      con,
      "UPDATE continuous.measurements_calculated_daily
       SET measurement_row_id = DEFAULT
       WHERE measurement_row_id IS NULL;"
    )
    message("Stable row identifiers added to measurements_calculated_daily.")
    message(
      "Done populating row identifiers for existing measurements."
    )
    DBI::dbExecute(
      con,
      "ALTER TABLE continuous.measurements_continuous
       ALTER COLUMN measurement_row_id SET NOT NULL;"
    )
    DBI::dbExecute(
      con,
      "ALTER TABLE continuous.measurements_calculated_daily
       ALTER COLUMN measurement_row_id SET NOT NULL;"
    )

    DBI::dbExecute(
      con,
      "COMMENT ON COLUMN continuous.measurements_continuous.measurement_row_id IS
       'Stable internal row identifier assigned once and used to reconstruct measurement history when the natural key changes over time.';"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON COLUMN continuous.measurements_calculated_daily.measurement_row_id IS
       'Stable internal row identifier assigned once and used to reconstruct stored daily history when the natural key changes over time.';"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON COLUMN audit.measurements_continuous_log.measurement_row_id IS
       'Stable immutable measurement row identifier copied from continuous.measurements_continuous to support point-in-time reconstruction across key changes.';"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON COLUMN audit.measurements_calculated_daily_log.measurement_row_id IS
       'Stable immutable measurement row identifier copied from continuous.measurements_calculated_daily to support point-in-time reconstruction across key changes.';"
    )

    message(
      "\nAdding indexes and updating audit triggers to use the new stable row identifiers. This will also take a while."
    )
    DBI::dbExecute(
      con,
      "CREATE UNIQUE INDEX IF NOT EXISTS
       measurements_continuous_measurement_row_id_idx
       ON continuous.measurements_continuous (measurement_row_id);"
    )
    message(
      "\nUnique index added on measurements_continuous.measurement_row_id."
    )
    DBI::dbExecute(
      con,
      "CREATE UNIQUE INDEX IF NOT EXISTS
       measurements_calculated_daily_measurement_row_id_idx
       ON continuous.measurements_calculated_daily (measurement_row_id);"
    )
    message(
      "\nUnique index added on measurements_calculated_daily.measurement_row_id. The rest of this patch should be faster now."
    )
    DBI::dbExecute(
      con,
      "CREATE INDEX IF NOT EXISTS
       measurements_continuous_log_measurement_row_id_action_ts_idx
       ON audit.measurements_continuous_log (
         measurement_row_id,
         action_timestamp,
         log_id
       )
       WHERE measurement_row_id IS NOT NULL;"
    )
    DBI::dbExecute(
      con,
      "CREATE INDEX IF NOT EXISTS
       mcd_log_measurement_row_id_action_ts_idx
       ON audit.measurements_calculated_daily_log (
         measurement_row_id,
         action_timestamp,
         log_id
       )
       WHERE measurement_row_id IS NOT NULL;"
    )
    DBI::dbExecute(
      con,
      "CREATE OR REPLACE FUNCTION public.prevent_measurement_row_id_change()
       RETURNS TRIGGER
       LANGUAGE plpgsql
       AS $function$
       BEGIN
         IF OLD.measurement_row_id IS DISTINCT FROM NEW.measurement_row_id THEN
           RAISE EXCEPTION
             'measurement_row_id is immutable on %.%. Attempted to change % to %.',
             TG_TABLE_SCHEMA,
             TG_TABLE_NAME,
             OLD.measurement_row_id,
             NEW.measurement_row_id;
         END IF;

         RETURN NEW;
       END;
       $function$;"
    )
    DBI::dbExecute(
      con,
      "ALTER FUNCTION public.prevent_measurement_row_id_change()
       OWNER TO admin;"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON FUNCTION public.prevent_measurement_row_id_change() IS
       'Prevents updates to measurement_row_id so audit history remains keyed to one stable row identifier per measurement row.';"
    )
    DBI::dbExecute(
      con,
      "DROP TRIGGER IF EXISTS prevent_measurements_continuous_row_id_change
       ON continuous.measurements_continuous;"
    )
    DBI::dbExecute(
      con,
      "CREATE TRIGGER prevent_measurements_continuous_row_id_change
       BEFORE UPDATE OF measurement_row_id ON continuous.measurements_continuous
       FOR EACH ROW
       EXECUTE FUNCTION public.prevent_measurement_row_id_change();"
    )
    DBI::dbExecute(
      con,
      "DROP TRIGGER IF EXISTS prevent_measurements_calculated_daily_row_id_change
       ON continuous.measurements_calculated_daily;"
    )
    DBI::dbExecute(
      con,
      "CREATE TRIGGER prevent_measurements_calculated_daily_row_id_change
       BEFORE UPDATE OF measurement_row_id ON continuous.measurements_calculated_daily
       FOR EACH ROW
       EXECUTE FUNCTION public.prevent_measurement_row_id_change();"
    )

    DBI::dbExecute(
      con,
      "CREATE OR REPLACE FUNCTION audit.if_modified_func()
       RETURNS TRIGGER
       LANGUAGE plpgsql
       SECURITY DEFINER
       SET search_path = pg_catalog, public, audit
       AS $function$
       DECLARE
         v_user_name TEXT := current_user::TEXT;
         v_actor_user TEXT := COALESCE(
           NULLIF(current_setting('aquacache.audit_user', true), ''),
           session_user::TEXT
         );
         v_application_name TEXT := NULLIF(
           current_setting('application_name', true),
           ''
         );
         v_skip_audit BOOLEAN := FALSE;
         v_row_created TIMESTAMPTZ;
         v_row_modified TIMESTAMPTZ;
         v_old_data JSONB;
         v_new_data JSONB;
         v_changed_fields JSONB;
         v_old_end_dt TIMESTAMPTZ;
         v_new_end_dt TIMESTAMPTZ;
         v_segment_start_dt TIMESTAMPTZ;
         v_timeseries_id INTEGER;
       BEGIN
         IF TG_OP = 'DELETE' THEN
           v_row_created := (to_jsonb(OLD) ->> 'created')::timestamptz;
           v_row_modified := (to_jsonb(OLD) ->> 'modified')::timestamptz;
           v_old_data := to_jsonb(OLD)
             - 'created' - 'modified' - 'created_by' - 'modified_by';

           INSERT INTO audit.general_log (
             schema_name,
             table_name,
             user_name,
             actor_user,
             application_name,
             action,
             row_created,
             row_modified,
             original_data,
             new_data,
             changed_fields,
             action_timestamp,
             transaction_id
           ) VALUES (
             TG_TABLE_SCHEMA,
             TG_TABLE_NAME,
             v_user_name,
             v_actor_user,
             v_application_name,
             TG_OP,
             v_row_created,
             v_row_modified,
             v_old_data,
             NULL,
             NULL,
             clock_timestamp(),
             txid_current()
           );

           RETURN OLD;
         END IF;

         v_row_created := COALESCE(
           (to_jsonb(NEW) ->> 'created')::timestamptz,
           (to_jsonb(OLD) ->> 'created')::timestamptz
         );
         v_row_modified := COALESCE(
           (to_jsonb(NEW) ->> 'modified')::timestamptz,
           (to_jsonb(OLD) ->> 'modified')::timestamptz
         );
         v_old_data := to_jsonb(OLD)
           - 'created' - 'modified' - 'created_by' - 'modified_by';
         v_new_data := to_jsonb(NEW)
           - 'created' - 'modified' - 'created_by' - 'modified_by';

         -- Ignore automatically maintained sync timestamps on timeseries
         IF TG_TABLE_SCHEMA = 'continuous' AND TG_TABLE_NAME = 'timeseries' THEN
           v_old_data := v_old_data
             - 'last_new_data' - 'last_synchronize' - 'last_daily_calculation' - 'end_datetime' - 'start_datetime' - 'last_synchronize' - 'last_new_data' - 'last_daily_calculation';
           v_new_data := v_new_data
             - 'last_new_data' - 'last_synchronize' - 'last_daily_calculation' - 'end_datetime' - 'start_datetime' - 'last_synchronize' - 'last_new_data' - 'last_daily_calculation';
         END IF;

         v_changed_fields := audit.jsonb_changed_fields(v_old_data, v_new_data);

         -- Skip noisy sync-style updates that only extend the latest
         -- temporal segment on qualifying metadata tables.
         IF
           TG_OP = 'UPDATE' AND
             TG_TABLE_SCHEMA = 'continuous' AND
             TG_TABLE_NAME = ANY(ARRAY[
               'approvals',
               'grades',
               'qualifiers',
               'owners',
               'contributors'
             ]) AND
             jsonb_object_length(v_changed_fields) = 1 AND
             v_changed_fields ? 'end_dt'
         THEN
           v_old_end_dt := (to_jsonb(OLD) ->> 'end_dt')::timestamptz;
           v_new_end_dt := (to_jsonb(NEW) ->> 'end_dt')::timestamptz;
           v_segment_start_dt := (to_jsonb(NEW) ->> 'start_dt')::timestamptz;
           v_timeseries_id := (to_jsonb(NEW) ->> 'timeseries_id')::integer;

           IF v_new_end_dt > v_old_end_dt THEN
             EXECUTE format(
               'SELECT NOT EXISTS (
                  SELECT 1
                  FROM %I.%I t
                  WHERE t.timeseries_id = $1
                    AND t.start_dt > $2
                )',
               TG_TABLE_SCHEMA,
               TG_TABLE_NAME
             )
             INTO v_skip_audit
             USING v_timeseries_id, v_segment_start_dt;
           END IF;
         END IF;

         IF v_changed_fields = '{}'::jsonb THEN
           RETURN NEW;
         END IF;

         IF v_skip_audit THEN
           RETURN NEW;
         END IF;

         INSERT INTO audit.general_log (
           schema_name,
           table_name,
           user_name,
           actor_user,
           application_name,
           action,
           row_created,
           row_modified,
           original_data,
           new_data,
           changed_fields,
           action_timestamp,
           transaction_id
         ) VALUES (
           TG_TABLE_SCHEMA,
           TG_TABLE_NAME,
           v_user_name,
           v_actor_user,
           v_application_name,
           TG_OP,
           v_row_created,
           v_row_modified,
           v_old_data,
           v_new_data,
           v_changed_fields,
           clock_timestamp(),
           txid_current()
         );

         RETURN NEW;
       END;
       $function$;"
    )
    DBI::dbExecute(
      con,
      "ALTER FUNCTION audit.if_modified_func() OWNER TO admin;"
    )

    DBI::dbExecute(
      con,
      "CREATE OR REPLACE FUNCTION audit.log_measurements_continuous_change()
       RETURNS TRIGGER
       LANGUAGE plpgsql
       SECURITY DEFINER
       SET search_path = pg_catalog, public, audit
       AS $function$
       DECLARE
         v_user_name TEXT := current_user::TEXT;
         v_actor_user TEXT := COALESCE(
           NULLIF(current_setting('aquacache.audit_user', true), ''),
           session_user::TEXT
         );
         v_application_name TEXT := NULLIF(
           current_setting('application_name', true),
           ''
         );
         v_measurement_row_id BIGINT;
         v_timeseries_id INTEGER;
         v_measurement_datetime TIMESTAMPTZ;
         v_old_data JSONB;
         v_new_data JSONB;
         v_changed_fields JSONB;
       BEGIN
         IF TG_OP = 'DELETE' THEN
           v_measurement_row_id := OLD.measurement_row_id;
           v_timeseries_id := OLD.timeseries_id;
           v_measurement_datetime := OLD.datetime;
           INSERT INTO audit.measurements_continuous_log (
             measurement_row_id,
             timeseries_id,
             measurement_datetime,
             user_name,
             actor_user,
             application_name,
             action,
             action_timestamp,
             original_data,
             new_data,
             changed_fields,
             transaction_id
           ) VALUES (
             v_measurement_row_id,
             v_timeseries_id,
             v_measurement_datetime,
             v_user_name,
             v_actor_user,
             v_application_name,
             TG_OP,
             clock_timestamp(),
             to_jsonb(OLD),
             NULL,
             NULL,
             txid_current()
           );

           RETURN OLD;
         END IF;

         v_old_data := to_jsonb(OLD);
         v_new_data := to_jsonb(NEW);
         v_measurement_row_id := OLD.measurement_row_id;
         v_timeseries_id := OLD.timeseries_id;
         v_measurement_datetime := OLD.datetime;
         v_changed_fields := audit.jsonb_changed_fields(v_old_data, v_new_data);

         IF v_changed_fields = '{}'::jsonb THEN
           RETURN NEW;
         END IF;

         INSERT INTO audit.measurements_continuous_log (
           measurement_row_id,
           timeseries_id,
           measurement_datetime,
           user_name,
           actor_user,
           application_name,
           action,
           action_timestamp,
           original_data,
           new_data,
           changed_fields,
           transaction_id
         ) VALUES (
           v_measurement_row_id,
           v_timeseries_id,
           v_measurement_datetime,
           v_user_name,
           v_actor_user,
           v_application_name,
           TG_OP,
           clock_timestamp(),
           v_old_data,
           v_new_data,
           v_changed_fields,
           txid_current()
         );

         RETURN NEW;
       END;
       $function$;"
    )
    DBI::dbExecute(
      con,
      "ALTER FUNCTION audit.log_measurements_continuous_change() OWNER TO admin;"
    )

    DBI::dbExecute(
      con,
      "CREATE OR REPLACE FUNCTION audit.log_measurements_calculated_daily_change()
       RETURNS TRIGGER
       LANGUAGE plpgsql
       SECURITY DEFINER
       SET search_path = pg_catalog, public, audit
       AS $function$
       DECLARE
         v_user_name TEXT := current_user::TEXT;
         v_actor_user TEXT := COALESCE(
           NULLIF(current_setting('aquacache.audit_user', true), ''),
           session_user::TEXT
         );
         v_application_name TEXT := NULLIF(
           current_setting('application_name', true),
           ''
         );
         v_measurement_row_id BIGINT;
         v_timeseries_id INTEGER;
         v_measurement_date DATE;
         v_old_data JSONB;
         v_new_data JSONB;
         v_changed_fields JSONB;
       BEGIN
         IF TG_OP = 'DELETE' THEN
           v_measurement_row_id := OLD.measurement_row_id;
           v_timeseries_id := OLD.timeseries_id;
           v_measurement_date := OLD.date;
           INSERT INTO audit.measurements_calculated_daily_log (
             measurement_row_id,
             timeseries_id,
             measurement_date,
             user_name,
             actor_user,
             application_name,
             action,
             action_timestamp,
             original_data,
             new_data,
             changed_fields,
             transaction_id
           ) VALUES (
             v_measurement_row_id,
             v_timeseries_id,
             v_measurement_date,
             v_user_name,
             v_actor_user,
             v_application_name,
             TG_OP,
             clock_timestamp(),
             to_jsonb(OLD),
             NULL,
             NULL,
             txid_current()
           );

           RETURN OLD;
         END IF;

         v_old_data := to_jsonb(OLD);
         v_new_data := to_jsonb(NEW);
         v_measurement_row_id := OLD.measurement_row_id;
         v_timeseries_id := OLD.timeseries_id;
         v_measurement_date := OLD.date;
         v_changed_fields := audit.jsonb_changed_fields(v_old_data, v_new_data);

         IF v_changed_fields = '{}'::jsonb THEN
           RETURN NEW;
         END IF;

         INSERT INTO audit.measurements_calculated_daily_log (
           measurement_row_id,
           timeseries_id,
           measurement_date,
           user_name,
           actor_user,
           application_name,
           action,
           action_timestamp,
           original_data,
           new_data,
           changed_fields,
           transaction_id
         ) VALUES (
           v_measurement_row_id,
           v_timeseries_id,
           v_measurement_date,
           v_user_name,
           v_actor_user,
           v_application_name,
           TG_OP,
           clock_timestamp(),
           v_old_data,
           v_new_data,
           v_changed_fields,
           txid_current()
         );

         RETURN NEW;
       END;
       $function$;"
    )
    DBI::dbExecute(
      con,
      "ALTER FUNCTION audit.log_measurements_calculated_daily_change() OWNER TO admin;"
    )
    DBI::dbExecute(
      con,
      "CREATE TRIGGER audit_measurements_continuous_trigger
       AFTER UPDATE OR DELETE ON continuous.measurements_continuous
       FOR EACH ROW
       EXECUTE FUNCTION audit.log_measurements_continuous_change();"
    )
    DBI::dbExecute(
      con,
      "CREATE TRIGGER audit_measurements_calculated_daily_trigger
       AFTER UPDATE OR DELETE ON continuous.measurements_calculated_daily
       FOR EACH ROW
       EXECUTE FUNCTION audit.log_measurements_calculated_daily_change();"
    )

    DBI::dbExecute(
      con,
      "DROP TRIGGER IF EXISTS audit_corrections_trigger
       ON continuous.corrections;"
    )
    DBI::dbExecute(
      con,
      "CREATE TRIGGER audit_corrections_trigger
       AFTER UPDATE OR DELETE ON continuous.corrections
       FOR EACH ROW
       EXECUTE FUNCTION audit.if_modified_func();"
    )
    DBI::dbExecute(
      con,
      "DROP TRIGGER IF EXISTS audit_correction_types_trigger
       ON continuous.correction_types;"
    )
    DBI::dbExecute(
      con,
      "CREATE TRIGGER audit_correction_types_trigger
       AFTER UPDATE OR DELETE ON continuous.correction_types
       FOR EACH ROW
       EXECUTE FUNCTION audit.if_modified_func();"
    )

    DBI::dbExecute(
      con,
      "CREATE INDEX IF NOT EXISTS general_log_corrections_asof_idx
       ON audit.general_log (
         (COALESCE(
           (original_data ->> 'timeseries_id')::integer,
           (new_data ->> 'timeseries_id')::integer
         )),
         action_timestamp DESC,
         (COALESCE(
           (original_data ->> 'correction_id')::integer,
           (new_data ->> 'correction_id')::integer
         ))
       )
       WHERE schema_name = 'continuous'
         AND table_name = 'corrections';"
    )
    DBI::dbExecute(
      con,
      "CREATE INDEX IF NOT EXISTS general_log_correction_types_asof_idx
       ON audit.general_log (
         (COALESCE(
           (original_data ->> 'correction_type_id')::integer,
           (new_data ->> 'correction_type_id')::integer
         )),
         action_timestamp DESC
       )
       WHERE schema_name = 'continuous'
         AND table_name = 'correction_types';"
    )

    # Historical snapshot helpers ###########################################
    DBI::dbExecute(
      con,
      "CREATE OR REPLACE FUNCTION audit.measurements_continuous_as_of(
         p_as_of TIMESTAMPTZ,
         p_timeseries_ids INTEGER[] DEFAULT NULL,
         p_start_datetime TIMESTAMPTZ DEFAULT NULL,
         p_end_datetime TIMESTAMPTZ DEFAULT NULL
       )
       RETURNS TABLE (
         timeseries_id INTEGER,
         datetime TIMESTAMPTZ,
         value NUMERIC,
         period INTERVAL,
         imputed BOOLEAN,
         no_update BOOLEAN,
         created_by TEXT,
         modified_by TEXT,
         created TIMESTAMPTZ,
         modified TIMESTAMPTZ
       )
       LANGUAGE plpgsql
       STABLE
       SET search_path = pg_catalog, public, continuous, audit
       AS $function$
       BEGIN
         RETURN QUERY EXECUTE
         $sql$
           WITH candidate_row_ids AS (
             SELECT mc.measurement_row_id
             FROM continuous.measurements_continuous mc
             WHERE ($1 IS NULL OR mc.timeseries_id = ANY($1))
               AND ($2 IS NULL OR mc.datetime >= $2)
               AND ($3 IS NULL OR mc.datetime <= $3)
             UNION
             SELECT log.measurement_row_id
             FROM audit.measurements_continuous_log log
             WHERE log.measurement_row_id IS NOT NULL
               AND log.action_timestamp > $4
               AND (
                 $1 IS NULL OR
                   (log.original_data ->> 'timeseries_id')::integer = ANY($1)
               )
               AND (
                 $2 IS NULL OR
                   (log.original_data ->> 'datetime')::timestamptz >= $2
               )
               AND (
                 $3 IS NULL OR
                   (log.original_data ->> 'datetime')::timestamptz <= $3
               )
           ),
           current_rows AS (
             SELECT
               mc.measurement_row_id,
               to_jsonb(mc) AS row_json,
               mc.created AS row_created
             FROM continuous.measurements_continuous mc
             JOIN candidate_row_ids ids
               ON ids.measurement_row_id = mc.measurement_row_id
           ),
           future_changes AS (
             SELECT DISTINCT ON (log.measurement_row_id)
               log.measurement_row_id,
               log.original_data AS row_json,
               NULLIF(log.original_data ->> 'created', '')::timestamptz AS row_created
             FROM audit.measurements_continuous_log log
             JOIN candidate_row_ids ids
               ON ids.measurement_row_id = log.measurement_row_id
             WHERE log.measurement_row_id IS NOT NULL
               AND log.action_timestamp > $4
             ORDER BY
               log.measurement_row_id,
               log.action_timestamp ASC,
               log.log_id ASC
           ),
           snapshot_json AS (
             SELECT
               COALESCE(f.measurement_row_id, c.measurement_row_id) AS measurement_row_id,
               COALESCE(f.row_json, c.row_json) AS row_json,
               COALESCE(f.row_created, c.row_created) AS row_created
             FROM current_rows c
             FULL OUTER JOIN future_changes f
               ON c.measurement_row_id = f.measurement_row_id
           )
           SELECT
             r.timeseries_id,
             r.datetime,
             r.value,
             r.period,
             r.imputed,
             r.no_update,
             r.created_by,
             r.modified_by,
             r.created,
             r.modified
           FROM snapshot_json s
           CROSS JOIN LATERAL jsonb_populate_record(
             NULL::continuous.measurements_continuous,
             s.row_json
           ) AS r
           WHERE COALESCE(r.created, s.row_created) <= $4
             AND ($1 IS NULL OR r.timeseries_id = ANY($1))
             AND ($2 IS NULL OR r.datetime >= $2)
             AND ($3 IS NULL OR r.datetime <= $3)
           ORDER BY r.timeseries_id, r.datetime
         $sql$
         USING p_timeseries_ids, p_start_datetime, p_end_datetime, p_as_of;
       END;
       $function$;"
    )
    DBI::dbExecute(
      con,
      "ALTER FUNCTION audit.measurements_continuous_as_of(
         TIMESTAMPTZ,
         INTEGER[],
         TIMESTAMPTZ,
         TIMESTAMPTZ
       ) OWNER TO admin;"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON FUNCTION audit.measurements_continuous_as_of(
         TIMESTAMPTZ,
         INTEGER[],
         TIMESTAMPTZ,
         TIMESTAMPTZ
       ) IS
       'Reconstructs raw continuous measurement rows as they existed at a requested timestamp using the current table plus audit.measurements_continuous_log. Implemented with dynamic execution so filtered calls use a custom plan.';"
    )

    DBI::dbExecute(
      con,
      "CREATE OR REPLACE FUNCTION audit.measurements_calculated_daily_as_of(
         p_as_of TIMESTAMPTZ,
         p_timeseries_ids INTEGER[] DEFAULT NULL,
         p_start_date DATE DEFAULT NULL,
         p_end_date DATE DEFAULT NULL
       )
       RETURNS TABLE (
         timeseries_id INTEGER,
         date DATE,
         value NUMERIC,
         imputed BOOLEAN,
         percent_historic_range NUMERIC,
         max NUMERIC,
         min NUMERIC,
         q90 NUMERIC,
         q75 NUMERIC,
         q50 NUMERIC,
         q25 NUMERIC,
         q10 NUMERIC,
         mean NUMERIC,
         doy_count INTEGER,
         no_update BOOLEAN,
         created_by TEXT,
         modified_by TEXT,
         created TIMESTAMPTZ,
         modified TIMESTAMPTZ
       )
       LANGUAGE plpgsql
       STABLE
       SET search_path = pg_catalog, public, continuous, audit
       AS $function$
       BEGIN
         RETURN QUERY EXECUTE
         $sql$
           WITH candidate_row_ids AS (
             SELECT mcd.measurement_row_id
             FROM continuous.measurements_calculated_daily mcd
             WHERE ($1 IS NULL OR mcd.timeseries_id = ANY($1))
               AND ($2 IS NULL OR mcd.date >= $2)
               AND ($3 IS NULL OR mcd.date <= $3)
             UNION
             SELECT log.measurement_row_id
             FROM audit.measurements_calculated_daily_log log
             WHERE log.measurement_row_id IS NOT NULL
               AND log.action_timestamp > $4
               AND (
                 $1 IS NULL OR
                   (log.original_data ->> 'timeseries_id')::integer = ANY($1)
               )
               AND (
                 $2 IS NULL OR
                   (log.original_data ->> 'date')::date >= $2
               )
               AND (
                 $3 IS NULL OR
                   (log.original_data ->> 'date')::date <= $3
               )
           ),
           current_rows AS (
             SELECT
               mcd.measurement_row_id,
               to_jsonb(mcd) AS row_json,
               mcd.created AS row_created
             FROM continuous.measurements_calculated_daily mcd
             JOIN candidate_row_ids ids
               ON ids.measurement_row_id = mcd.measurement_row_id
           ),
           future_changes AS (
             SELECT DISTINCT ON (log.measurement_row_id)
               log.measurement_row_id,
               log.original_data AS row_json,
               NULLIF(log.original_data ->> 'created', '')::timestamptz AS row_created
             FROM audit.measurements_calculated_daily_log log
             JOIN candidate_row_ids ids
               ON ids.measurement_row_id = log.measurement_row_id
             WHERE log.measurement_row_id IS NOT NULL
               AND log.action_timestamp > $4
             ORDER BY
               log.measurement_row_id,
               log.action_timestamp ASC,
               log.log_id ASC
           ),
           snapshot_json AS (
             SELECT
               COALESCE(f.measurement_row_id, c.measurement_row_id) AS measurement_row_id,
               COALESCE(f.row_json, c.row_json) AS row_json,
               COALESCE(f.row_created, c.row_created) AS row_created
             FROM current_rows c
             FULL OUTER JOIN future_changes f
               ON c.measurement_row_id = f.measurement_row_id
           )
           SELECT
             r.timeseries_id,
             r.date,
             r.value,
             r.imputed,
             r.percent_historic_range,
             r.max,
             r.min,
             r.q90,
             r.q75,
             r.q50,
             r.q25,
             r.q10,
             r.mean,
             r.doy_count,
             r.no_update,
             r.created_by,
             r.modified_by,
             r.created,
             r.modified
           FROM snapshot_json s
           CROSS JOIN LATERAL jsonb_populate_record(
             NULL::continuous.measurements_calculated_daily,
             s.row_json
           ) AS r
           WHERE COALESCE(r.created, s.row_created) <= $4
             AND ($1 IS NULL OR r.timeseries_id = ANY($1))
             AND ($2 IS NULL OR r.date >= $2)
             AND ($3 IS NULL OR r.date <= $3)
           ORDER BY r.timeseries_id, r.date
         $sql$
         USING p_timeseries_ids, p_start_date, p_end_date, p_as_of;
       END;
       $function$;"
    )
    DBI::dbExecute(
      con,
      "ALTER FUNCTION audit.measurements_calculated_daily_as_of(
         TIMESTAMPTZ,
         INTEGER[],
         DATE,
         DATE
       ) OWNER TO admin;"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON FUNCTION audit.measurements_calculated_daily_as_of(
         TIMESTAMPTZ,
         INTEGER[],
         DATE,
         DATE
       ) IS
       'Reconstructs stored calculated daily rows as they existed at a requested timestamp using the current table plus audit.measurements_calculated_daily_log. It does not recompute daily values and uses dynamic execution so filtered calls use a custom plan.';"
    )

    DBI::dbExecute(
      con,
      "CREATE OR REPLACE FUNCTION audit.corrections_as_of(
         p_as_of TIMESTAMPTZ,
         p_timeseries_ids INTEGER[] DEFAULT NULL
       )
       RETURNS TABLE (
         correction_id INTEGER,
         timeseries_id INTEGER,
         start_dt TIMESTAMPTZ,
         end_dt TIMESTAMPTZ,
         correction_type INTEGER,
         value1 NUMERIC,
         value2 NUMERIC,
         timestep_window INTERVAL,
         equation TEXT,
         created TIMESTAMPTZ,
         updated TIMESTAMPTZ,
         modified TIMESTAMPTZ
       )
       LANGUAGE sql
       STABLE
       SET search_path = pg_catalog, public, continuous, audit
       AS $function$
         WITH current_rows AS (
           SELECT
             c.correction_id,
             c.timeseries_id,
             to_jsonb(c) AS row_json,
             c.created AS row_created
           FROM continuous.corrections c
           WHERE (p_timeseries_ids IS NULL OR c.timeseries_id = ANY(p_timeseries_ids))
         ),
         future_changes AS (
           SELECT DISTINCT ON (x.correction_id)
             x.correction_id,
             x.timeseries_id,
             x.row_json,
             x.row_created
           FROM (
             SELECT
               COALESCE(
                 (g.original_data ->> 'correction_id')::integer,
                 (g.new_data ->> 'correction_id')::integer
               ) AS correction_id,
               COALESCE(
                 (g.original_data ->> 'timeseries_id')::integer,
                 (g.new_data ->> 'timeseries_id')::integer
               ) AS timeseries_id,
               g.original_data ||
                 jsonb_strip_nulls(
                   jsonb_build_object(
                     'created', g.row_created,
                     'modified', g.row_modified
                   )
                 ) AS row_json,
               g.row_created,
               g.action_timestamp,
               g.log_id
             FROM audit.general_log g
             WHERE g.schema_name = 'continuous'
               AND g.table_name = 'corrections'
               AND g.action_timestamp > p_as_of
               AND (
                 p_timeseries_ids IS NULL
                 OR COALESCE(
                   (g.original_data ->> 'timeseries_id')::integer,
                   (g.new_data ->> 'timeseries_id')::integer
                 ) = ANY(p_timeseries_ids)
               )
           ) x
           ORDER BY x.correction_id, x.action_timestamp ASC, x.log_id ASC
         ),
         snapshot_json AS (
           SELECT
             COALESCE(f.correction_id, c.correction_id) AS correction_id,
             COALESCE(f.timeseries_id, c.timeseries_id) AS timeseries_id,
             COALESCE(f.row_json, c.row_json) AS row_json,
             COALESCE(f.row_created, c.row_created) AS row_created
           FROM current_rows c
           FULL OUTER JOIN future_changes f
             ON c.correction_id = f.correction_id
         )
         SELECT
           r.correction_id,
           r.timeseries_id,
           r.start_dt,
           r.end_dt,
           r.correction_type,
           r.value1,
           r.value2,
           r.timestep_window,
           r.equation,
           r.created,
           r.updated,
           r.modified
         FROM snapshot_json s
         CROSS JOIN LATERAL jsonb_to_record(s.row_json) AS r(
           correction_id INTEGER,
           timeseries_id INTEGER,
           start_dt TIMESTAMPTZ,
           end_dt TIMESTAMPTZ,
           correction_type INTEGER,
           value1 NUMERIC,
           value2 NUMERIC,
           timestep_window INTERVAL,
           equation TEXT,
           created TIMESTAMPTZ,
           updated TIMESTAMPTZ,
           modified TIMESTAMPTZ
         )
         WHERE COALESCE(r.created, s.row_created) <= p_as_of
         ORDER BY r.timeseries_id, r.start_dt, r.correction_id;
       $function$;"
    )
    DBI::dbExecute(
      con,
      "ALTER FUNCTION audit.corrections_as_of(
         TIMESTAMPTZ,
         INTEGER[]
       ) OWNER TO admin;"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON FUNCTION audit.corrections_as_of(
         TIMESTAMPTZ,
         INTEGER[]
       ) IS
       'Reconstructs corrections rows as they existed at a requested timestamp using continuous.corrections plus audit.general_log.';"
    )

    DBI::dbExecute(
      con,
      "CREATE OR REPLACE FUNCTION audit.correction_types_as_of(
         p_as_of TIMESTAMPTZ
       )
       RETURNS TABLE (
         correction_type_id INTEGER,
         correction_type TEXT,
         description TEXT,
         priority INTEGER,
         value1 BOOLEAN,
         value1_description TEXT,
         value2 BOOLEAN,
         value2_description TEXT,
         timestep_window BOOLEAN,
         equation BOOLEAN,
         created TIMESTAMPTZ,
         updated TIMESTAMPTZ,
         modified TIMESTAMPTZ
       )
       LANGUAGE sql
       STABLE
       SET search_path = pg_catalog, public, continuous, audit
       AS $function$
         WITH current_rows AS (
           SELECT
             ct.correction_type_id,
             to_jsonb(ct) AS row_json,
             ct.created AS row_created
           FROM continuous.correction_types ct
         ),
         future_changes AS (
           SELECT DISTINCT ON (x.correction_type_id)
             x.correction_type_id,
             x.row_json,
             x.row_created
           FROM (
             SELECT
               COALESCE(
                 (g.original_data ->> 'correction_type_id')::integer,
                 (g.new_data ->> 'correction_type_id')::integer
               ) AS correction_type_id,
               g.original_data ||
                 jsonb_strip_nulls(
                   jsonb_build_object(
                     'created', g.row_created,
                     'modified', g.row_modified
                   )
                 ) AS row_json,
               g.row_created,
               g.action_timestamp,
               g.log_id
             FROM audit.general_log g
             WHERE g.schema_name = 'continuous'
               AND g.table_name = 'correction_types'
               AND g.action_timestamp > p_as_of
           ) x
           ORDER BY
             x.correction_type_id,
             x.action_timestamp ASC,
             x.log_id ASC
         ),
         snapshot_json AS (
           SELECT
             COALESCE(f.correction_type_id, c.correction_type_id) AS correction_type_id,
             COALESCE(f.row_json, c.row_json) AS row_json,
             COALESCE(f.row_created, c.row_created) AS row_created
           FROM current_rows c
           FULL OUTER JOIN future_changes f
             ON c.correction_type_id = f.correction_type_id
         )
         SELECT
           r.correction_type_id,
           r.correction_type,
           r.description,
           r.priority,
           r.value1,
           r.value1_description,
           r.value2,
           r.value2_description,
           r.timestep_window,
           r.equation,
           r.created,
           r.updated,
           r.modified
         FROM snapshot_json s
         CROSS JOIN LATERAL jsonb_to_record(s.row_json) AS r(
           correction_type_id INTEGER,
           correction_type TEXT,
           description TEXT,
           priority INTEGER,
           value1 BOOLEAN,
           value1_description TEXT,
           value2 BOOLEAN,
           value2_description TEXT,
           timestep_window BOOLEAN,
           equation BOOLEAN,
           created TIMESTAMPTZ,
           updated TIMESTAMPTZ,
           modified TIMESTAMPTZ
         )
         WHERE COALESCE(r.created, s.row_created) <= p_as_of
         ORDER BY r.priority, r.correction_type_id;
       $function$;"
    )
    DBI::dbExecute(
      con,
      "ALTER FUNCTION audit.correction_types_as_of(
         TIMESTAMPTZ
       ) OWNER TO admin;"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON FUNCTION audit.correction_types_as_of(
         TIMESTAMPTZ
       ) IS
       'Reconstructs correction_types rows as they existed at a requested timestamp using continuous.correction_types plus audit.general_log.';"
    )

    # Public historical access functions ####################################
    DBI::dbExecute(
      con,
      "CREATE OR REPLACE FUNCTION continuous.apply_corrections_at(
         p_as_of TIMESTAMPTZ,
         p_timeseries_id INTEGER,
         p_datetime TIMESTAMPTZ,
         p_value NUMERIC
       )
       RETURNS NUMERIC
       LANGUAGE plpgsql
       STABLE
       SECURITY INVOKER
       SET search_path = continuous, audit, pg_catalog
       AS $function$
       DECLARE
         corrected_value NUMERIC := p_value;
         correction_row RECORD;
         time_since_start NUMERIC;
         time_window NUMERIC;
         rate NUMERIC;
         correction NUMERIC;
       BEGIN
         IF p_value IS NULL THEN
           RETURN NULL;
         END IF;

         FOR correction_row IN
           SELECT
             c.correction_id,
             c.value1 AS c_value1,
             c.value2 AS c_value2,
             c.timestep_window AS c_timestep_window,
             c.equation AS c_equation,
             c.start_dt,
             c.end_dt,
             ct.correction_type,
             ct.priority
           FROM audit.corrections_as_of(
             p_as_of,
             ARRAY[p_timeseries_id]
           ) c
           JOIN audit.correction_types_as_of(p_as_of) ct
             ON c.correction_type = ct.correction_type_id
           WHERE c.timeseries_id = p_timeseries_id
             AND c.start_dt <= p_datetime
             AND COALESCE(c.end_dt, 'infinity'::timestamptz) >= p_datetime
           ORDER BY ct.priority ASC, c.correction_id ASC
         LOOP
           IF correction_row.correction_type = 'delete' THEN
             RETURN NULL;

           ELSIF correction_row.correction_type = 'trim' THEN
             IF correction_row.c_value1 IS NOT NULL AND corrected_value < correction_row.c_value1 THEN
               RETURN NULL;
             ELSIF correction_row.c_value2 IS NOT NULL AND corrected_value > correction_row.c_value2 THEN
               RETURN NULL;
             END IF;

           ELSIF correction_row.correction_type = 'offset linear' THEN
             corrected_value := corrected_value + correction_row.c_value1;

           ELSIF correction_row.correction_type = 'offset two-point' THEN
             time_since_start := EXTRACT(
               EPOCH FROM (p_datetime - correction_row.start_dt)
             );
             time_window := EXTRACT(
               EPOCH FROM (
                 COALESCE(correction_row.end_dt, p_datetime) -
                 correction_row.start_dt
               )
             );
             IF time_window <= 0 THEN
               RAISE EXCEPTION 'Invalid time window for offset two-point correction';
             END IF;
             rate := (
               correction_row.c_value2 - correction_row.c_value1
             ) / time_window;
             correction := correction_row.c_value1 +
               rate * time_since_start;
             corrected_value := corrected_value + correction;

           ELSIF correction_row.correction_type = 'scale' THEN
             corrected_value := corrected_value *
               (correction_row.c_value1 / 100.0);

           ELSIF correction_row.correction_type = 'drift linear' THEN
             IF p_datetime < correction_row.start_dt
               OR p_datetime > COALESCE(
                 correction_row.end_dt,
                 'infinity'::timestamptz
               ) THEN
               correction := 0;
             ELSE
               time_since_start := EXTRACT(
                 EPOCH FROM (p_datetime - correction_row.start_dt)
               );
               time_window := EXTRACT(
                 EPOCH FROM correction_row.c_timestep_window
               );
               IF time_window <= 0 THEN
                 RAISE EXCEPTION 'Invalid timestep_window for drift linear correction';
               END IF;
               rate := correction_row.c_value1 / time_window;
               correction := rate * time_since_start;
             END IF;
             corrected_value := corrected_value + correction;

           ELSIF correction_row.correction_type = 'drift equation' THEN
             time_since_start := EXTRACT(
               EPOCH FROM (p_datetime - correction_row.start_dt)
             );
             EXECUTE format('SELECT %s', correction_row.c_equation)
               INTO correction
               USING corrected_value, time_since_start;
             corrected_value := correction;

           ELSE
             RAISE NOTICE 'Correction type % not handled',
               correction_row.correction_type;
           END IF;
         END LOOP;

         RETURN corrected_value;
       END;
       $function$;"
    )
    DBI::dbExecute(
      con,
      "ALTER FUNCTION continuous.apply_corrections_at(
         TIMESTAMPTZ,
         INTEGER,
         TIMESTAMPTZ,
         NUMERIC
       ) OWNER TO admin;"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON FUNCTION continuous.apply_corrections_at(
         TIMESTAMPTZ,
         INTEGER,
         TIMESTAMPTZ,
         NUMERIC
       ) IS
       'Applies the corrections that existed at a requested timestamp to one continuous measurement value.';"
    )

    DBI::dbExecute(
      con,
      "CREATE OR REPLACE FUNCTION continuous.measurements_continuous_corrected_at(
         p_as_of TIMESTAMPTZ,
         p_timeseries_ids INTEGER[] DEFAULT NULL,
         p_start_datetime TIMESTAMPTZ DEFAULT NULL,
         p_end_datetime TIMESTAMPTZ DEFAULT NULL
       )
       RETURNS TABLE (
         timeseries_id INTEGER,
         datetime TIMESTAMPTZ,
         value_raw NUMERIC,
         value_corrected NUMERIC,
         period INTERVAL,
         imputed BOOLEAN,
         created TIMESTAMPTZ,
         modified TIMESTAMPTZ
       )
       LANGUAGE sql
       STABLE
       SECURITY INVOKER
       SET search_path = pg_catalog, public, continuous, audit
       AS $function$
         WITH visible_timeseries AS (
           SELECT ts.timeseries_id
           FROM continuous.timeseries ts
           WHERE (p_timeseries_ids IS NULL OR ts.timeseries_id = ANY(p_timeseries_ids))
         )
         SELECT
           mc.timeseries_id,
           mc.datetime,
           mc.value AS value_raw,
           continuous.apply_corrections_at(
             p_as_of,
             mc.timeseries_id,
             mc.datetime,
             mc.value
           ) AS value_corrected,
           mc.period,
           mc.imputed,
           mc.created,
           mc.modified
         FROM audit.measurements_continuous_as_of(
           p_as_of,
           p_timeseries_ids,
           p_start_datetime,
           p_end_datetime
         ) mc
         JOIN visible_timeseries vt
           ON mc.timeseries_id = vt.timeseries_id
         ORDER BY mc.timeseries_id, mc.datetime;
       $function$;"
    )
    DBI::dbExecute(
      con,
      "ALTER FUNCTION continuous.measurements_continuous_corrected_at(
         TIMESTAMPTZ,
         INTEGER[],
         TIMESTAMPTZ,
         TIMESTAMPTZ
       ) OWNER TO admin;"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON FUNCTION continuous.measurements_continuous_corrected_at(
         TIMESTAMPTZ,
         INTEGER[],
         TIMESTAMPTZ,
         TIMESTAMPTZ
       ) IS
       'Returns the continuous measurement rows that existed at a requested timestamp, with the corrections that existed at that same timestamp applied. Visibility is filtered through the caller''s current access to continuous.timeseries.';"
    )

    DBI::dbExecute(
      con,
      "CREATE OR REPLACE FUNCTION continuous.measurements_calculated_daily_corrected_at(
         p_as_of TIMESTAMPTZ,
         p_timeseries_ids INTEGER[] DEFAULT NULL,
         p_start_date DATE DEFAULT NULL,
         p_end_date DATE DEFAULT NULL
       )
       RETURNS TABLE (
         timeseries_id INTEGER,
         date DATE,
         value NUMERIC,
         imputed BOOLEAN,
         percent_historic_range NUMERIC,
         max NUMERIC,
         min NUMERIC,
         q90 NUMERIC,
         q75 NUMERIC,
         q50 NUMERIC,
         q25 NUMERIC,
         q10 NUMERIC,
         mean NUMERIC,
         doy_count INTEGER,
         created TIMESTAMPTZ,
         modified TIMESTAMPTZ
       )
       LANGUAGE sql
       STABLE
       SECURITY INVOKER
       SET search_path = pg_catalog, public, continuous, audit
       AS $function$
         WITH visible_timeseries AS (
           SELECT ts.timeseries_id
           FROM continuous.timeseries ts
           WHERE (p_timeseries_ids IS NULL OR ts.timeseries_id = ANY(p_timeseries_ids))
         )
         SELECT
           mcd.timeseries_id,
           mcd.date,
           mcd.value,
           mcd.imputed,
           mcd.percent_historic_range,
           mcd.max,
           mcd.min,
           mcd.q90,
           mcd.q75,
           mcd.q50,
           mcd.q25,
           mcd.q10,
           mcd.mean,
           mcd.doy_count,
           mcd.created,
           mcd.modified
         FROM audit.measurements_calculated_daily_as_of(
           p_as_of,
           p_timeseries_ids,
           p_start_date,
           p_end_date
         ) mcd
         JOIN visible_timeseries vt
           ON mcd.timeseries_id = vt.timeseries_id
         ORDER BY mcd.timeseries_id, mcd.date;
       $function$;"
    )
    DBI::dbExecute(
      con,
      "ALTER FUNCTION continuous.measurements_calculated_daily_corrected_at(
         TIMESTAMPTZ,
         INTEGER[],
         DATE,
         DATE
       ) OWNER TO admin;"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON FUNCTION continuous.measurements_calculated_daily_corrected_at(
         TIMESTAMPTZ,
         INTEGER[],
         DATE,
         DATE
       ) IS
       'Returns the stored calculated daily rows that existed at a requested timestamp. It does not recompute daily values. Visibility is filtered through the caller''s current access to continuous.timeseries.';"
    )

    # Function privileges ###################################################
    function_grants <- c(
      paste0(
        "REVOKE ALL ON FUNCTION audit.measurements_continuous_as_of(",
        "TIMESTAMPTZ, INTEGER[], TIMESTAMPTZ, TIMESTAMPTZ",
        ") FROM PUBLIC;"
      ),
      paste0(
        "REVOKE ALL ON FUNCTION audit.measurements_calculated_daily_as_of(",
        "TIMESTAMPTZ, INTEGER[], DATE, DATE",
        ") FROM PUBLIC;"
      ),
      paste0(
        "REVOKE ALL ON FUNCTION audit.corrections_as_of(",
        "TIMESTAMPTZ, INTEGER[]",
        ") FROM PUBLIC;"
      ),
      paste0(
        "REVOKE ALL ON FUNCTION audit.correction_types_as_of(",
        "TIMESTAMPTZ",
        ") FROM PUBLIC;"
      ),
      paste0(
        "REVOKE ALL ON FUNCTION continuous.apply_corrections_at(",
        "TIMESTAMPTZ, INTEGER, TIMESTAMPTZ, NUMERIC",
        ") FROM PUBLIC;"
      ),
      paste0(
        "REVOKE ALL ON FUNCTION continuous.measurements_continuous_corrected_at(",
        "TIMESTAMPTZ, INTEGER[], TIMESTAMPTZ, TIMESTAMPTZ",
        ") FROM PUBLIC;"
      ),
      paste0(
        "REVOKE ALL ON FUNCTION continuous.measurements_calculated_daily_corrected_at(",
        "TIMESTAMPTZ, INTEGER[], DATE, DATE",
        ") FROM PUBLIC;"
      )
    )
    for (sql in function_grants) {
      DBI::dbExecute(con, sql)
    }

    for (role_name in historical_function_roles) {
      quoted_role <- as.character(DBI::dbQuoteIdentifier(con, role_name))
      DBI::dbExecute(
        con,
        sprintf(
          "GRANT EXECUTE ON FUNCTION audit.measurements_continuous_as_of(TIMESTAMPTZ, INTEGER[], TIMESTAMPTZ, TIMESTAMPTZ) TO %s;",
          quoted_role
        )
      )
      DBI::dbExecute(
        con,
        sprintf(
          "GRANT EXECUTE ON FUNCTION audit.measurements_calculated_daily_as_of(TIMESTAMPTZ, INTEGER[], DATE, DATE) TO %s;",
          quoted_role
        )
      )
      DBI::dbExecute(
        con,
        sprintf(
          "GRANT EXECUTE ON FUNCTION audit.corrections_as_of(TIMESTAMPTZ, INTEGER[]) TO %s;",
          quoted_role
        )
      )
      DBI::dbExecute(
        con,
        sprintf(
          "GRANT EXECUTE ON FUNCTION audit.correction_types_as_of(TIMESTAMPTZ) TO %s;",
          quoted_role
        )
      )
      DBI::dbExecute(
        con,
        sprintf(
          "GRANT EXECUTE ON FUNCTION continuous.apply_corrections_at(TIMESTAMPTZ, INTEGER, TIMESTAMPTZ, NUMERIC) TO %s;",
          quoted_role
        )
      )
      DBI::dbExecute(
        con,
        sprintf(
          "GRANT EXECUTE ON FUNCTION continuous.measurements_continuous_corrected_at(TIMESTAMPTZ, INTEGER[], TIMESTAMPTZ, TIMESTAMPTZ) TO %s;",
          quoted_role
        )
      )
      DBI::dbExecute(
        con,
        sprintf(
          "GRANT EXECUTE ON FUNCTION continuous.measurements_calculated_daily_corrected_at(TIMESTAMPTZ, INTEGER[], DATE, DATE) TO %s;",
          quoted_role
        )
      )
    }

    # Wrap things up ########################################################
    DBI::dbExecute(
      con,
      "UPDATE information.version_info SET version = '38'
       WHERE item = 'Last patch number';"
    )
    DBI::dbExecute(
      con,
      paste0(
        "UPDATE information.version_info SET version = '",
        as.character(packageVersion("AquaCache")),
        "' WHERE item = 'AquaCache R package used for last patch';"
      )
    )

    # Commit the transaction
    DBI::dbExecute(con, "COMMIT;")

    message("Patch 38 applied successfully, transaction closed.")
  },
  error = function(e) {
    # Rollback the transaction
    DBI::dbExecute(con, "ROLLBACK;")
    stop(
      "Patch 38 failed and the DB has been rolled back to its earlier state. ",
      e$message
    )
  }
)
