# Patch 49: database-backed source import parameter mappings

check <- DBI::dbGetQuery(con, "SELECT SESSION_USER")

if (check$session_user != "postgres") {
  stop(
    "You do not have the necessary privileges for this patch. Connect as postgres user to make this work."
  )
}

message(
  "Working on patch 49: adding flexible, database-backed import parameter mapping tables."
)

if (dbTransCheck(con)) {
  stop(
    "A transaction is already in progress. Please commit or rollback the current transaction before applying this patch."
  )
}

active <- FALSE
active <- dbTransBegin(con)

tryCatch(
  {
    check <- DBI::dbGetQuery(
      con,
      "SELECT
         to_regclass('discrete.results') IS NOT NULL AS has_results,
         to_regclass('discrete.result_types') IS NOT NULL AS has_result_types,
         to_regclass('discrete.result_conditions') IS NOT NULL AS has_result_conditions,
         to_regclass('discrete.result_value_types') IS NOT NULL AS has_result_value_types,
         to_regclass('discrete.sample_fractions') IS NOT NULL AS has_sample_fractions,
         to_regclass('discrete.result_speciations') IS NOT NULL AS has_result_speciations,
         to_regclass('public.parameters') IS NOT NULL AS has_parameters,
         to_regclass('public.matrix_states') IS NOT NULL AS has_matrix_states,
         to_regclass('information.version_info') IS NOT NULL AS has_version_info"
    )

    if (
      !isTRUE(check$has_results[[1]]) ||
        !isTRUE(check$has_result_types[[1]]) ||
        !isTRUE(check$has_result_conditions[[1]]) ||
        !isTRUE(check$has_result_value_types[[1]]) ||
        !isTRUE(check$has_sample_fractions[[1]]) ||
        !isTRUE(check$has_result_speciations[[1]]) ||
        !isTRUE(check$has_parameters[[1]]) ||
        !isTRUE(check$has_matrix_states[[1]]) ||
        !isTRUE(check$has_version_info[[1]])
    ) {
      stop(
        "Patch 49 requires discrete results and lookup tables, public.parameters, public.matrix_states, and information.version_info to already exist."
      )
    }

    DBI::dbExecute(
      con,
      "ALTER TABLE discrete.results
       ADD COLUMN IF NOT EXISTS note TEXT;"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON COLUMN discrete.results.note IS
       'Optional source/result-level note. For imported data this can preserve lab flags, method comments, or other result-specific metadata from the source system.';"
    )

    DBI::dbExecute(
      con,
      "CREATE TABLE IF NOT EXISTS discrete.import_sources (
         import_source_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
         source_code TEXT NOT NULL UNIQUE,
         source_name TEXT NOT NULL,
         source_description TEXT,
         active BOOLEAN NOT NULL DEFAULT TRUE,
         created_by TEXT DEFAULT CURRENT_USER NOT NULL,
         modified_by TEXT,
         created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
         modified TIMESTAMP WITH TIME ZONE
       );"
    )

    DBI::dbExecute(
      con,
      "ALTER TABLE discrete.import_sources OWNER TO admin;"
    )

    DBI::dbExecute(
      con,
      "CREATE TABLE IF NOT EXISTS discrete.import_parameter_mappings (
         import_mapping_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
         import_source_id INTEGER NOT NULL
           REFERENCES discrete.import_sources(import_source_id)
           ON UPDATE CASCADE
           ON DELETE CASCADE,
         source_match JSONB NOT NULL,
         parameter_id INTEGER
           REFERENCES public.parameters(parameter_id)
           ON UPDATE CASCADE
           ON DELETE RESTRICT,
         result_type INTEGER NOT NULL
           REFERENCES discrete.result_types(result_type_id)
           ON UPDATE CASCADE
           ON DELETE RESTRICT,
         sample_fraction_id INTEGER
           REFERENCES discrete.sample_fractions(sample_fraction_id)
           ON UPDATE CASCADE
           ON DELETE RESTRICT,
         result_value_type INTEGER
           REFERENCES discrete.result_value_types(result_value_type_id)
           ON UPDATE CASCADE
           ON DELETE RESTRICT,
         result_speciation_id INTEGER
           REFERENCES discrete.result_speciations(result_speciation_id)
           ON UPDATE CASCADE
           ON DELETE RESTRICT,
         matrix_state_id INTEGER
           REFERENCES public.matrix_states(matrix_state_id)
           ON UPDATE CASCADE
           ON DELETE RESTRICT,
         conversion NUMERIC NOT NULL DEFAULT 1,
         result_offset NUMERIC NOT NULL DEFAULT 0,
         priority INTEGER NOT NULL DEFAULT 100,
         active BOOLEAN NOT NULL DEFAULT TRUE,
         note TEXT,
         created_by TEXT DEFAULT CURRENT_USER NOT NULL,
         modified_by TEXT,
         created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
         modified TIMESTAMP WITH TIME ZONE,
         CONSTRAINT import_parameter_mappings_source_match_object
           CHECK (jsonb_typeof(source_match) = 'object'),
         CONSTRAINT import_parameter_mappings_source_match_not_empty
           CHECK (source_match <> '{}'::jsonb),
         CONSTRAINT import_parameter_mappings_unique
           UNIQUE (import_source_id, source_match)
       );"
    )

    DBI::dbExecute(
      con,
      "ALTER TABLE discrete.import_parameter_mappings OWNER TO admin;"
    )

    DBI::dbExecute(
      con,
      "CREATE INDEX IF NOT EXISTS import_parameter_mappings_source_idx
       ON discrete.import_parameter_mappings (import_source_id);"
    )
    DBI::dbExecute(
      con,
      "CREATE INDEX IF NOT EXISTS import_parameter_mappings_parameter_idx
       ON discrete.import_parameter_mappings (parameter_id);"
    )
    DBI::dbExecute(
      con,
      "CREATE INDEX IF NOT EXISTS import_parameter_mappings_source_match_gin_idx
       ON discrete.import_parameter_mappings
       USING GIN (source_match jsonb_path_ops);"
    )

    DBI::dbExecute(
      con,
      "CREATE TABLE IF NOT EXISTS discrete.import_profiles (
         import_profile_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
         import_source_id INTEGER NOT NULL
           REFERENCES discrete.import_sources(import_source_id)
           ON UPDATE CASCADE
           ON DELETE CASCADE,
         profile_code TEXT NOT NULL,
         profile_name TEXT NOT NULL,
         profile_description TEXT,
         file_type TEXT NOT NULL DEFAULT 'xlsx'
           CHECK (file_type IN ('csv', 'tsv', 'txt', 'xlsx', 'xlsm', 'xls')),
         parser_type TEXT NOT NULL DEFAULT 'long'
           CHECK (parser_type IN ('long', 'wide', 'mixed')),
         sheet_strategy TEXT NOT NULL DEFAULT 'name_or_first'
           CHECK (sheet_strategy IN ('name', 'index', 'first', 'name_or_first', 'all')),
         sheet_name TEXT,
         sheet_index INTEGER CHECK (sheet_index IS NULL OR sheet_index > 0),
         header_row INTEGER NOT NULL DEFAULT 1 CHECK (header_row > 0),
         units_row INTEGER CHECK (units_row IS NULL OR units_row > 0),
         parameter_row INTEGER CHECK (parameter_row IS NULL OR parameter_row > 0),
         data_start_row INTEGER NOT NULL DEFAULT 2 CHECK (data_start_row > 0),
         datetime_origin TEXT NOT NULL DEFAULT 'excel_1900'
           CHECK (datetime_origin IN ('excel_1900', 'excel_1904', 'text', 'posix', 'date_time_columns')),
         timezone TEXT NOT NULL DEFAULT 'UTC',
         column_map JSONB NOT NULL DEFAULT '{}'::jsonb,
         wide_config JSONB NOT NULL DEFAULT '{}'::jsonb,
         defaults JSONB NOT NULL DEFAULT '{}'::jsonb,
         sample_identity JSONB NOT NULL DEFAULT
           '[\"location_id\", \"sub_location_id\", \"media_id\", \"z\", \"datetime\", \"sample_type\", \"collection_method\"]'::jsonb,
         result_identity JSONB NOT NULL DEFAULT
           '[\"result_type\", \"parameter_id\", \"matrix_state_id\", \"sample_fraction_id\", \"result_value_type\", \"result_speciation_id\", \"protocol_method\", \"laboratory\", \"analysis_datetime\"]'::jsonb,
         validation_rules JSONB NOT NULL DEFAULT '{}'::jsonb,
         active BOOLEAN NOT NULL DEFAULT TRUE,
         note TEXT,
         created_by TEXT DEFAULT CURRENT_USER NOT NULL,
         modified_by TEXT,
         created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
         modified TIMESTAMP WITH TIME ZONE,
         CONSTRAINT import_profiles_unique
           UNIQUE (import_source_id, profile_code),
         CONSTRAINT import_profiles_column_map_object
           CHECK (jsonb_typeof(column_map) = 'object'),
         CONSTRAINT import_profiles_wide_config_object
           CHECK (jsonb_typeof(wide_config) = 'object'),
         CONSTRAINT import_profiles_defaults_object
           CHECK (jsonb_typeof(defaults) = 'object'),
         CONSTRAINT import_profiles_sample_identity_array
           CHECK (jsonb_typeof(sample_identity) = 'array'),
         CONSTRAINT import_profiles_result_identity_array
           CHECK (jsonb_typeof(result_identity) = 'array'),
         CONSTRAINT import_profiles_validation_rules_object
           CHECK (jsonb_typeof(validation_rules) = 'object')
       );"
    )

    DBI::dbExecute(
      con,
      "ALTER TABLE discrete.import_profiles OWNER TO admin;"
    )
    DBI::dbExecute(
      con,
      "CREATE INDEX IF NOT EXISTS import_profiles_source_idx
       ON discrete.import_profiles (import_source_id);"
    )
    DBI::dbExecute(
      con,
      "CREATE INDEX IF NOT EXISTS import_profiles_column_map_gin_idx
       ON discrete.import_profiles USING GIN (column_map jsonb_path_ops);"
    )

    DBI::dbExecute(
      con,
      "CREATE TABLE IF NOT EXISTS discrete.import_qualifier_mappings (
         import_qualifier_mapping_id INTEGER PRIMARY KEY
           GENERATED BY DEFAULT AS IDENTITY,
         import_source_id INTEGER NOT NULL
           REFERENCES discrete.import_sources(import_source_id)
           ON UPDATE CASCADE
           ON DELETE CASCADE,
         import_profile_id INTEGER
           REFERENCES discrete.import_profiles(import_profile_id)
           ON UPDATE CASCADE
           ON DELETE CASCADE,
         qualifier_column TEXT,
         qualifier_value TEXT NOT NULL,
         result_condition INTEGER
           REFERENCES discrete.result_conditions(result_condition_id)
           ON UPDATE CASCADE
           ON DELETE RESTRICT,
         result_condition_value_source TEXT NOT NULL DEFAULT 'none'
           CHECK (result_condition_value_source IN ('none', 'result', 'method_detection_limit', 'reporting_detection_limit', 'literal')),
         result_condition_value_literal NUMERIC,
         result_action TEXT NOT NULL DEFAULT 'keep_result'
           CHECK (result_action IN ('keep_result', 'set_result_null', 'skip_result', 'reject_row', 'note_only')),
         note_template TEXT,
         priority INTEGER NOT NULL DEFAULT 100,
         active BOOLEAN NOT NULL DEFAULT TRUE,
         note TEXT,
         created_by TEXT DEFAULT CURRENT_USER NOT NULL,
         modified_by TEXT,
         created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
         modified TIMESTAMP WITH TIME ZONE,
         CONSTRAINT import_qualifier_mappings_unique
           UNIQUE NULLS NOT DISTINCT (
             import_source_id,
             import_profile_id,
             qualifier_column,
             qualifier_value
           )
       );"
    )

    DBI::dbExecute(
      con,
      "ALTER TABLE discrete.import_qualifier_mappings OWNER TO admin;"
    )
    DBI::dbExecute(
      con,
      "CREATE INDEX IF NOT EXISTS import_qualifier_mappings_source_idx
       ON discrete.import_qualifier_mappings (import_source_id);"
    )
    DBI::dbExecute(
      con,
      "CREATE INDEX IF NOT EXISTS import_qualifier_mappings_profile_idx
       ON discrete.import_qualifier_mappings (import_profile_id);"
    )

    DBI::dbExecute(
      con,
      "CREATE TABLE IF NOT EXISTS discrete.import_upload_sessions (
         import_upload_session_id INTEGER PRIMARY KEY
           GENERATED BY DEFAULT AS IDENTITY,
         import_profile_id INTEGER NOT NULL
           REFERENCES discrete.import_profiles(import_profile_id)
           ON UPDATE CASCADE
           ON DELETE RESTRICT,
         source_file_name TEXT,
         source_file_hash TEXT,
         source_file_size BIGINT,
         status TEXT NOT NULL DEFAULT 'created'
           CHECK (status IN ('created', 'previewed', 'validated', 'committed', 'failed', 'cancelled')),
         summary JSONB NOT NULL DEFAULT '{}'::jsonb,
         validation_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
         committed_at TIMESTAMP WITH TIME ZONE,
         note TEXT,
         created_by TEXT DEFAULT CURRENT_USER NOT NULL,
         modified_by TEXT,
         created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
         modified TIMESTAMP WITH TIME ZONE,
         CONSTRAINT import_upload_sessions_summary_object
           CHECK (jsonb_typeof(summary) = 'object'),
         CONSTRAINT import_upload_sessions_validation_summary_object
           CHECK (jsonb_typeof(validation_summary) = 'object')
       );"
    )

    DBI::dbExecute(
      con,
      "ALTER TABLE discrete.import_upload_sessions OWNER TO admin;"
    )
    DBI::dbExecute(
      con,
      "CREATE INDEX IF NOT EXISTS import_upload_sessions_profile_idx
       ON discrete.import_upload_sessions (import_profile_id);"
    )
    DBI::dbExecute(
      con,
      "CREATE INDEX IF NOT EXISTS import_upload_sessions_status_idx
       ON discrete.import_upload_sessions (status);"
    )

    DBI::dbExecute(
      con,
      "CREATE TABLE IF NOT EXISTS discrete.import_upload_rows (
         import_upload_row_id INTEGER PRIMARY KEY
           GENERATED BY DEFAULT AS IDENTITY,
         import_upload_session_id INTEGER NOT NULL
           REFERENCES discrete.import_upload_sessions(import_upload_session_id)
           ON UPDATE CASCADE
           ON DELETE CASCADE,
         sheet_name TEXT,
         source_row_number INTEGER,
         result_index INTEGER NOT NULL DEFAULT 1,
         source_record JSONB NOT NULL DEFAULT '{}'::jsonb,
         normalized_sample JSONB NOT NULL DEFAULT '{}'::jsonb,
         normalized_result JSONB NOT NULL DEFAULT '{}'::jsonb,
         validation_status TEXT NOT NULL DEFAULT 'pending'
           CHECK (validation_status IN ('pending', 'valid', 'warning', 'error', 'skipped', 'committed')),
         validation_messages JSONB NOT NULL DEFAULT '[]'::jsonb,
         sample_id INTEGER
           REFERENCES discrete.samples(sample_id)
           ON UPDATE CASCADE
           ON DELETE SET NULL,
         result_id INTEGER
           REFERENCES discrete.results(result_id)
           ON UPDATE CASCADE
           ON DELETE SET NULL,
         created_by TEXT DEFAULT CURRENT_USER NOT NULL,
         modified_by TEXT,
         created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
         modified TIMESTAMP WITH TIME ZONE,
         CONSTRAINT import_upload_rows_unique
           UNIQUE NULLS NOT DISTINCT (
             import_upload_session_id,
             sheet_name,
             source_row_number,
             result_index
           ),
         CONSTRAINT import_upload_rows_source_record_object
           CHECK (jsonb_typeof(source_record) = 'object'),
         CONSTRAINT import_upload_rows_normalized_sample_object
           CHECK (jsonb_typeof(normalized_sample) = 'object'),
         CONSTRAINT import_upload_rows_normalized_result_object
           CHECK (jsonb_typeof(normalized_result) = 'object'),
         CONSTRAINT import_upload_rows_validation_messages_array
           CHECK (jsonb_typeof(validation_messages) = 'array')
       );"
    )

    DBI::dbExecute(
      con,
      "ALTER TABLE discrete.import_upload_rows OWNER TO admin;"
    )
    DBI::dbExecute(
      con,
      "CREATE INDEX IF NOT EXISTS import_upload_rows_session_idx
       ON discrete.import_upload_rows (import_upload_session_id);"
    )
    DBI::dbExecute(
      con,
      "CREATE INDEX IF NOT EXISTS import_upload_rows_status_idx
       ON discrete.import_upload_rows (validation_status);"
    )

    DBI::dbExecute(
      con,
      "DROP TRIGGER IF EXISTS trg_user_audit
       ON discrete.import_sources;"
    )
    DBI::dbExecute(
      con,
      "CREATE TRIGGER trg_user_audit
       BEFORE UPDATE ON discrete.import_sources
       FOR EACH ROW EXECUTE FUNCTION public.user_modified();"
    )
    DBI::dbExecute(
      con,
      "DROP TRIGGER IF EXISTS update_modify_time
       ON discrete.import_sources;"
    )
    DBI::dbExecute(
      con,
      "CREATE TRIGGER update_modify_time
       BEFORE UPDATE ON discrete.import_sources
       FOR EACH ROW EXECUTE FUNCTION public.update_modified();"
    )

    DBI::dbExecute(
      con,
      "DROP TRIGGER IF EXISTS trg_user_audit
       ON discrete.import_parameter_mappings;"
    )
    DBI::dbExecute(
      con,
      "CREATE TRIGGER trg_user_audit
       BEFORE UPDATE ON discrete.import_parameter_mappings
       FOR EACH ROW EXECUTE FUNCTION public.user_modified();"
    )
    DBI::dbExecute(
      con,
      "DROP TRIGGER IF EXISTS update_modify_time
       ON discrete.import_parameter_mappings;"
    )
    DBI::dbExecute(
      con,
      "CREATE TRIGGER update_modify_time
       BEFORE UPDATE ON discrete.import_parameter_mappings
       FOR EACH ROW EXECUTE FUNCTION public.update_modified();"
    )

    for (audit_table in c(
      "import_profiles",
      "import_qualifier_mappings",
      "import_upload_sessions",
      "import_upload_rows"
    )) {
      DBI::dbExecute(
        con,
        paste0(
          "DROP TRIGGER IF EXISTS trg_user_audit
           ON discrete.",
          audit_table,
          ";"
        )
      )
      DBI::dbExecute(
        con,
        paste0(
          "CREATE TRIGGER trg_user_audit
           BEFORE UPDATE ON discrete.",
          audit_table,
          "
           FOR EACH ROW EXECUTE FUNCTION public.user_modified();"
        )
      )
      DBI::dbExecute(
        con,
        paste0(
          "DROP TRIGGER IF EXISTS update_modify_time
           ON discrete.",
          audit_table,
          ";"
        )
      )
      DBI::dbExecute(
        con,
        paste0(
          "CREATE TRIGGER update_modify_time
           BEFORE UPDATE ON discrete.",
          audit_table,
          "
           FOR EACH ROW EXECUTE FUNCTION public.update_modified();"
        )
      )
    }

    DBI::dbExecute(
      con,
      "COMMENT ON TABLE discrete.import_sources IS
       'External source systems with parameter mappings used by AquaCache import functions.';"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON TABLE discrete.import_parameter_mappings IS
       'Maps source-system result identifiers to AquaCache discrete result foreign keys. Source-side criteria are stored as a JSON object so each external database can match on its own required columns.';"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON COLUMN discrete.import_parameter_mappings.source_match IS
       'JSON object containing the source-side fields that identify this mapping, such as input_param/input_unit for ECCC or any richer combination required by another source.';"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON COLUMN discrete.import_parameter_mappings.conversion IS
       'Multiplier applied to the source numeric result before insertion into AquaCache.';"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON COLUMN discrete.import_parameter_mappings.result_offset IS
       'Offset added after conversion when a source requires a linear result transform: source value * conversion + result_offset.';"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON COLUMN discrete.import_parameter_mappings.priority IS
       'Lower values are preferred when multiple mappings match the same source record.';"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON TABLE discrete.import_profiles IS
       'Reusable file import profiles for Shiny and scripted imports. Profiles describe sheet layout, column mapping, defaults, and validation behaviour separately from parameter mappings.';"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON COLUMN discrete.import_profiles.column_map IS
       'JSON object mapping AquaCache staging fields to source workbook columns. This supports Shiny column-selection UIs and scripted imports without schema changes for each lab format.';"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON COLUMN discrete.import_profiles.wide_config IS
       'JSON object describing wide-format parameter columns, such as metadata columns to keep, parameter-code rows, units rows, and how to pivot result columns to long form.';"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON COLUMN discrete.import_profiles.defaults IS
       'JSON object of profile-level defaults such as media_id, collection_method, sample_type, owner, contributor, laboratory, result_type, matrix_state_id, and no_update.';"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON TABLE discrete.import_qualifier_mappings IS
       'Maps source lab qualifier or flag values to AquaCache result conditions, note behaviour, or row-level import actions.';"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON TABLE discrete.import_upload_sessions IS
       'Optional persistent Shiny/script upload session log for lab import previews, validation summaries, and committed import metadata.';"
    )
    DBI::dbExecute(
      con,
      "COMMENT ON TABLE discrete.import_upload_rows IS
       'Optional per-row staging table for source records, normalized sample/result JSON, validation messages, and committed sample/result IDs.';"
    )

    q_ident <- function(x) {
      as.character(DBI::dbQuoteIdentifier(con, x))
    }
    grant_roles <- DBI::dbGetQuery(
      con,
      "SELECT rolname
       FROM pg_roles
       WHERE rolname IN ('public_reader')
       ORDER BY rolname;"
    )$rolname

    for (role in intersect(
      c("public_reader"),
      grant_roles
    )) {
      DBI::dbExecute(
        con,
        paste0(
          "GRANT SELECT ON discrete.import_sources TO ",
          q_ident(role),
          ";"
        )
      )
      DBI::dbExecute(
        con,
        paste0(
          "GRANT SELECT ON discrete.import_parameter_mappings TO ",
          q_ident(role),
          ";"
        )
      )
      for (tbl in c(
        "import_profiles",
        "import_qualifier_mappings",
        "import_upload_sessions",
        "import_upload_rows"
      )) {
        DBI::dbExecute(
          con,
          paste0(
            "GRANT SELECT ON discrete.",
            tbl,
            " TO ",
            q_ident(role),
            ";"
          )
        )
      }
    }

    kmh <- DBI::dbGetQuery(
      con,
      "SELECT unit_id FROM public.units WHERE unit_name = 'km/h'"
    )$unit_id
    DBI::dbExecute(
      con,
      "UPDATE parameters SET units_gas = $1 WHERE param_name = 'velocity, wind'",
      params = list(kmh)
    )
    # Set units_liquid to NULL
    DBI::dbExecute(
      con,
      "UPDATE parameters SET units_liquid = NULL WHERE param_name = 'velocity, wind'"
    )

    # Add the 'downloadECCCeq1.csv' key to the database for starters
    # Find the file first
    mappings <- system.file(
      "import_keys",
      "downloadECCCeq1.csv",
      package = "AquaCache"
    )
    if (file.exists(mappings)) {
      upsertImportParameterMappings(
        con,
        source_code = "downloadECCCeq1",
        mappings = mappings,
        match_columns = c("input_param", "input_unit")
      )
    }

    DBI::dbExecute(
      con,
      "UPDATE information.version_info SET version = '49'
       WHERE item = 'Last patch number';"
    )
    DBI::dbExecute(
      con,
      paste0(
        "UPDATE information.version_info SET version = '",
        as.character(packageVersion('AquaCache')),
        "' WHERE item = 'AquaCache R package used for last patch';"
      )
    )

    DBI::dbExecute(con, "COMMIT;")
    active <- FALSE

    message(
      "Patch 49 applied successfully. Import parameter mappings can now be stored in discrete.import_sources and discrete.import_parameter_mappings."
    )
  },
  error = function(e) {
    if (isTRUE(active)) {
      message("Error detected. Rolling back active transaction...")
      try(DBI::dbExecute(con, "ROLLBACK"), silent = TRUE)
    }
    stop(e)
  }
)

# Convert ECCC wind-related data from m/s to km/h
ts <- DBI::dbGetQuery(
  con,
  "SELECT timeseries_id FROM timeseries WHERE source_fx IN ('downloadECCCwx', 'downloadECCCwxMinute') AND parameter_id = 1154"
)$timeseries_id

if (length(ts) > 0) {
  message(
    "Adjusting ECCC wind speed data from m/s to km/h for ",
    length(ts),
    " timeseries..."
  )
  # Acquire an advisory lock to prevent concurrent updates to the same timeseries during the conversion

  lock_namespace <- "aquacache_timeseries"
  increment <- 1
  for (i in ts) {
    message("Processing timeseries ", increment, " of ", length(ts))
    lock_acquired <- FALSE
    tryCatch(
      {
        DBI::dbExecute(
          con,
          "SELECT pg_advisory_lock(hashtext($1), $2);",
          params = list(lock_namespace, i)
        )
        lock_acquired <- TRUE

        # Do the operation in place to table 'measurements_continuous'
        DBI::dbExecute(
          con,
          "UPDATE measurements_continuous SET value = value * 3.6 WHERE timeseries_id = $1",
          params = list(i)
        )
      },
      finally = {
        if (lock_acquired) {
          DBI::dbGetQuery(
            con,
            "SELECT pg_advisory_unlock(hashtext($1), $2);",
            params = list(lock_namespace, i)
          )
        }
      }
    )
    increment <- increment + 1
  }
}
